version: '3.8'

services:
  easyssh:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILDKIT_INLINE_CACHE: 1
    image: easyssh:latest
    container_name: easyssh
    ports:
      - "8520:8520"
    environment:
      - NODE_ENV=production
      - SERVER_ADDRESS=${SERVER_ADDRESS:-}  # 服务器地址，不配置则自动获取公网IP
      - JWT_SECRET=${JWT_SECRET:-your-jwt-secret-key-please-change-in-production}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY:-your-encryption-key-please-change-in-production}
    volumes:
      - easyssh_data:/app/server/data
      - easyssh_logs:/app/server/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8520/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  easyssh_data:
    driver: local
  easyssh_logs:
    driver: local
