version: '3.8'

services:
  easyssh:
    image: shanheee/easyssh:latest
    container_name: easyssh
    ports:
      - "8520:8520"
    environment:
      - NODE_ENV=production
      - JWT_SECRET=${JWT_SECRET:-your-jwt-secret-key-please-change-in-production}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY:-your-encryption-key-please-change-in-production}
    volumes:
      - ./easyssh/data:/app/server/data
      - ./easyssh/logs:/easyssh/logs
    restart: unless-stopped
