version: '3.8'

services:
  easyssh:
    image: shanheee/easyssh:latest
    container_name: easyssh
    ports:
      - "8520:8520"
    environment:
      - NODE_ENV=production
      - SERVER_ADDRESS=${SERVER_ADDRESS:-}  # 服务器地址，不配置则自动获取公网IP
      - JWT_SECRET=${JWT_SECRET:-your-jwt-secret-key-please-change-in-production}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY:-your-encryption-key-please-change-in-production}
    volumes:
      - ./data:/app/server/data
      - ./logs:/app/server/logs
    restart: unless-stopped
