import "@fontsource-variable/cascadia-code/wght.css"
import "@fontsource-variable/fira-code/wght.css"
import "@fontsource-variable/inter/wght.css"
import "@fontsource-variable/jetbrains-mono/wght.css"
import "@fontsource-variable/source-code-pro/wght.css"
