// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../time/models.js";

export type Record = { [_ in string]?: string };

export type Snapshot = { [_ in string]?: Record };

export class SyncScopes {
    "credentials": boolean;
    "ai_config": boolean;
    "sessions": boolean;

    /** Creates a new SyncScopes instance. */
    constructor($$source: Partial<SyncScopes> = {}) {
        if (!("credentials" in $$source)) {
            this["credentials"] = false;
        }
        if (!("ai_config" in $$source)) {
            this["ai_config"] = false;
        }
        if (!("sessions" in $$source)) {
            this["sessions"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SyncScopes instance from a string or object.
     */
    static createFrom($$source: any = {}): SyncScopes {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SyncScopes($$parsedSource as Partial<SyncScopes>);
    }
}

export class VaultConflict {
    "key": string;
    "field": string;
    "values": string[];
    "previews": { [_ in string]?: VaultSummary };

    /** Creates a new VaultConflict instance. */
    constructor($$source: Partial<VaultConflict> = {}) {
        if (!("key" in $$source)) {
            this["key"] = "";
        }
        if (!("field" in $$source)) {
            this["field"] = "";
        }
        if (!("values" in $$source)) {
            this["values"] = [];
        }
        if (!("previews" in $$source)) {
            this["previews"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new VaultConflict instance from a string or object.
     */
    static createFrom($$source: any = {}): VaultConflict {
        const $$createField2_0 = $$createType0;
        const $$createField3_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("values" in $$parsedSource) {
            $$parsedSource["values"] = $$createField2_0($$parsedSource["values"]);
        }
        if ("previews" in $$parsedSource) {
            $$parsedSource["previews"] = $$createField3_0($$parsedSource["previews"]);
        }
        return new VaultConflict($$parsedSource as Partial<VaultConflict>);
    }
}

/**
 * Summaries deliberately exclude passwords, private material, API keys and message bodies.
 */
export class VaultSummary {
    "source"?: string;
    "updated_at"?: time$0.Time | null;
    "deleted"?: boolean;
    "title"?: string;
    "messages"?: number;
    "last_message_at"?: time$0.Time | null;
    "has_password"?: boolean;
    "fingerprint"?: string;
    "provider"?: string;
    "has_api_key"?: boolean;

    /** Creates a new VaultSummary instance. */
    constructor($$source: Partial<VaultSummary> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new VaultSummary instance from a string or object.
     */
    static createFrom($$source: any = {}): VaultSummary {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new VaultSummary($$parsedSource as Partial<VaultSummary>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = VaultSummary.createFrom;
const $$createType2 = $Create.Map($Create.Any, $$createType1);
