// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Container {
    "id": string;
    "names": string[];
    "image": string;
    "imageId": string;
    "command": string;
    "created": number;
    "status": string;
    "state": string;
    "ports": Port[];
    "labels": { [_ in string]?: string };
    "mounts": Mount[];

    /** Creates a new Container instance. */
    constructor($$source: Partial<Container> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("names" in $$source)) {
            this["names"] = [];
        }
        if (!("image" in $$source)) {
            this["image"] = "";
        }
        if (!("imageId" in $$source)) {
            this["imageId"] = "";
        }
        if (!("command" in $$source)) {
            this["command"] = "";
        }
        if (!("created" in $$source)) {
            this["created"] = 0;
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("state" in $$source)) {
            this["state"] = "";
        }
        if (!("ports" in $$source)) {
            this["ports"] = [];
        }
        if (!("labels" in $$source)) {
            this["labels"] = {};
        }
        if (!("mounts" in $$source)) {
            this["mounts"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Container instance from a string or object.
     */
    static createFrom($$source: any = {}): Container {
        const $$createField1_0 = $$createType0;
        const $$createField8_0 = $$createType2;
        const $$createField9_0 = $$createType3;
        const $$createField10_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("names" in $$parsedSource) {
            $$parsedSource["names"] = $$createField1_0($$parsedSource["names"]);
        }
        if ("ports" in $$parsedSource) {
            $$parsedSource["ports"] = $$createField8_0($$parsedSource["ports"]);
        }
        if ("labels" in $$parsedSource) {
            $$parsedSource["labels"] = $$createField9_0($$parsedSource["labels"]);
        }
        if ("mounts" in $$parsedSource) {
            $$parsedSource["mounts"] = $$createField10_0($$parsedSource["mounts"]);
        }
        return new Container($$parsedSource as Partial<Container>);
    }
}

export class ContainerStats {
    "containerId": string;
    "name": string;
    "cpuPercent": number;
    "memoryUsage": number;
    "memoryLimit": number;
    "memoryPercent": number;
    "networkIn": number;
    "networkOut": number;
    "blockRead": number;
    "blockWrite": number;
    "pids": number;

    /** Creates a new ContainerStats instance. */
    constructor($$source: Partial<ContainerStats> = {}) {
        if (!("containerId" in $$source)) {
            this["containerId"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("cpuPercent" in $$source)) {
            this["cpuPercent"] = 0;
        }
        if (!("memoryUsage" in $$source)) {
            this["memoryUsage"] = 0;
        }
        if (!("memoryLimit" in $$source)) {
            this["memoryLimit"] = 0;
        }
        if (!("memoryPercent" in $$source)) {
            this["memoryPercent"] = 0;
        }
        if (!("networkIn" in $$source)) {
            this["networkIn"] = 0;
        }
        if (!("networkOut" in $$source)) {
            this["networkOut"] = 0;
        }
        if (!("blockRead" in $$source)) {
            this["blockRead"] = 0;
        }
        if (!("blockWrite" in $$source)) {
            this["blockWrite"] = 0;
        }
        if (!("pids" in $$source)) {
            this["pids"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ContainerStats instance from a string or object.
     */
    static createFrom($$source: any = {}): ContainerStats {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ContainerStats($$parsedSource as Partial<ContainerStats>);
    }
}

export class Image {
    "id": string;
    "repository": string;
    "tag": string;
    "created": number;
    "size": number;
    "virtualSize": number;

    /** Creates a new Image instance. */
    constructor($$source: Partial<Image> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("repository" in $$source)) {
            this["repository"] = "";
        }
        if (!("tag" in $$source)) {
            this["tag"] = "";
        }
        if (!("created" in $$source)) {
            this["created"] = 0;
        }
        if (!("size" in $$source)) {
            this["size"] = 0;
        }
        if (!("virtualSize" in $$source)) {
            this["virtualSize"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Image instance from a string or object.
     */
    static createFrom($$source: any = {}): Image {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Image($$parsedSource as Partial<Image>);
    }
}

export class Mount {
    "type": string;
    "source": string;
    "destination": string;
    "mode": string;
    "rw": boolean;

    /** Creates a new Mount instance. */
    constructor($$source: Partial<Mount> = {}) {
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("source" in $$source)) {
            this["source"] = "";
        }
        if (!("destination" in $$source)) {
            this["destination"] = "";
        }
        if (!("mode" in $$source)) {
            this["mode"] = "";
        }
        if (!("rw" in $$source)) {
            this["rw"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Mount instance from a string or object.
     */
    static createFrom($$source: any = {}): Mount {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Mount($$parsedSource as Partial<Mount>);
    }
}

export class Port {
    "ip"?: string;
    "privatePort": number;
    "publicPort"?: number;
    "type": string;

    /** Creates a new Port instance. */
    constructor($$source: Partial<Port> = {}) {
        if (!("privatePort" in $$source)) {
            this["privatePort"] = 0;
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Port instance from a string or object.
     */
    static createFrom($$source: any = {}): Port {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Port($$parsedSource as Partial<Port>);
    }
}

export class SystemInfo {
    "containersRunning": number;
    "containersPaused": number;
    "containersStopped": number;
    "containersTotal": number;
    "imagesCount": number;
    "dockerVersion": string;
    "serverVersion": string;
    "storageDriver": string;
    "totalMemory": number;
    "cpus": number;

    /** Creates a new SystemInfo instance. */
    constructor($$source: Partial<SystemInfo> = {}) {
        if (!("containersRunning" in $$source)) {
            this["containersRunning"] = 0;
        }
        if (!("containersPaused" in $$source)) {
            this["containersPaused"] = 0;
        }
        if (!("containersStopped" in $$source)) {
            this["containersStopped"] = 0;
        }
        if (!("containersTotal" in $$source)) {
            this["containersTotal"] = 0;
        }
        if (!("imagesCount" in $$source)) {
            this["imagesCount"] = 0;
        }
        if (!("dockerVersion" in $$source)) {
            this["dockerVersion"] = "";
        }
        if (!("serverVersion" in $$source)) {
            this["serverVersion"] = "";
        }
        if (!("storageDriver" in $$source)) {
            this["storageDriver"] = "";
        }
        if (!("totalMemory" in $$source)) {
            this["totalMemory"] = 0;
        }
        if (!("cpus" in $$source)) {
            this["cpus"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SystemInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): SystemInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SystemInfo($$parsedSource as Partial<SystemInfo>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = Port.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = $Create.Map($Create.Any, $Create.Any);
const $$createType4 = Mount.createFrom;
const $$createType5 = $Create.Array($$createType4);
