// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function CheckImageUpdate(input: $models.DesktopDockerContainerInput): $CancellablePromise<$models.DesktopDockerImageUpdateCheckResult> {
    return $Call.ByID(234349553, input).then(($result: any) => {
        return $$createType0($result);
    });
}

export function GetContainerLogs(input: $models.DesktopDockerContainerLogsInput): $CancellablePromise<$models.DesktopDockerContainerLogsResult> {
    return $Call.ByID(588678269, input).then(($result: any) => {
        return $$createType1($result);
    });
}

export function GetContainerStat(input: $models.DesktopDockerContainerInput): $CancellablePromise<$models.DesktopDockerContainerStats> {
    return $Call.ByID(87038732, input).then(($result: any) => {
        return $$createType2($result);
    });
}

export function GetContainerStats(input: $models.DesktopDockerServerInput): $CancellablePromise<$models.DesktopDockerContainerStats[]> {
    return $Call.ByID(2847623405, input).then(($result: any) => {
        return $$createType3($result);
    });
}

export function GetResources(input: $models.DesktopDockerServerInput): $CancellablePromise<$models.DesktopDockerResourcesResult> {
    return $Call.ByID(3687739276, input).then(($result: any) => {
        return $$createType4($result);
    });
}

export function GetSystemInfo(input: $models.DesktopDockerServerInput): $CancellablePromise<$models.DesktopDockerSystemInfo> {
    return $Call.ByID(4141604026, input).then(($result: any) => {
        return $$createType5($result);
    });
}

export function ListContainers(input: $models.DesktopDockerListContainersInput): $CancellablePromise<$models.DesktopDockerContainersResult> {
    return $Call.ByID(2330859537, input).then(($result: any) => {
        return $$createType6($result);
    });
}

export function ListImages(input: $models.DesktopDockerServerInput): $CancellablePromise<$models.DesktopDockerImagesResult> {
    return $Call.ByID(3149918571, input).then(($result: any) => {
        return $$createType7($result);
    });
}

export function PauseContainer(input: $models.DesktopDockerContainerInput): $CancellablePromise<void> {
    return $Call.ByID(3071849260, input);
}

export function RemoveContainer(input: $models.DesktopDockerRemoveContainerInput): $CancellablePromise<void> {
    return $Call.ByID(2422946236, input);
}

export function RestartContainer(input: $models.DesktopDockerContainerInput): $CancellablePromise<void> {
    return $Call.ByID(3654741143, input);
}

export function StartContainer(input: $models.DesktopDockerContainerInput): $CancellablePromise<void> {
    return $Call.ByID(532174070, input);
}

export function StopContainer(input: $models.DesktopDockerContainerInput): $CancellablePromise<void> {
    return $Call.ByID(126563580, input);
}

export function UnpauseContainer(input: $models.DesktopDockerContainerInput): $CancellablePromise<void> {
    return $Call.ByID(1862217295, input);
}

// Private type creation functions
const $$createType0 = $models.DesktopDockerImageUpdateCheckResult.createFrom;
const $$createType1 = $models.DesktopDockerContainerLogsResult.createFrom;
const $$createType2 = $models.DesktopDockerContainerStats.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = $models.DesktopDockerResourcesResult.createFrom;
const $$createType5 = $models.DesktopDockerSystemInfo.createFrom;
const $$createType6 = $models.DesktopDockerContainersResult.createFrom;
const $$createType7 = $models.DesktopDockerImagesResult.createFrom;
