// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function Close(input: $models.DesktopTerminalCloseInput): $CancellablePromise<void> {
    return $Call.ByID(2176147339, input);
}

export function FetchCompletionHistory(input: $models.DesktopTerminalCompletionHistoryInput): $CancellablePromise<$models.DesktopTerminalCompletionHistoryResult> {
    return $Call.ByID(2149225535, input).then(($result: any) => {
        return $$createType0($result);
    });
}

export function Ping(input: $models.DesktopTerminalPingInput): $CancellablePromise<$models.DesktopTerminalPingResult> {
    return $Call.ByID(2962857281, input).then(($result: any) => {
        return $$createType1($result);
    });
}

export function Resize(input: $models.DesktopTerminalResizeInput): $CancellablePromise<void> {
    return $Call.ByID(3001817145, input);
}

export function Start(input: $models.DesktopTerminalStartInput): $CancellablePromise<void> {
    return $Call.ByID(1081856935, input);
}

export function Write(input: $models.DesktopTerminalWriteInput): $CancellablePromise<void> {
    return $Call.ByID(822013716, input);
}

// Private type creation functions
const $$createType0 = $models.DesktopTerminalCompletionHistoryResult.createFrom;
const $$createType1 = $models.DesktopTerminalPingResult.createFrom;
