// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as syncdata$0 from "../shared/syncdata/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function BeginAuthorization(rawURL: string, name: string): $CancellablePromise<$models.DesktopSyncLogin> {
    return $Call.ByID(2122512864, rawURL, name).then(($result: any) => {
        return $$createType0($result);
    });
}

export function CancelAuthorization(): $CancellablePromise<void> {
    return $Call.ByID(96777289);
}

export function Candidates(): $CancellablePromise<$models.DesktopSyncCandidate[]> {
    return $Call.ByID(1237306864).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * Disconnect preserves each space's document and ownership, including offline edits.
 * An offline logout still removes the local credential; the UI reports whether
 * remote revocation succeeded so it can be retried from the Web device list.
 */
export function Disconnect(): $CancellablePromise<boolean> {
    return $Call.ByID(409323412);
}

/**
 * Enroll adds only explicitly selected local records. Records owned by another
 * space are copied with fresh IDs and without passwords or private-key links.
 */
export function Enroll(spaceID: string, keys: string[]): $CancellablePromise<void> {
    return $Call.ByID(872749506, spaceID, keys);
}

/**
 * Explicit copy into this space; never read an old account's configuration as
 * the configuration for a newly connected account.
 */
export function EnrollAIConfig(spaceID: string): $CancellablePromise<void> {
    return $Call.ByID(3253591838, spaceID);
}

export function EnrollSession(spaceID: string, localID: string): $CancellablePromise<void> {
    return $Call.ByID(3220310886, spaceID, localID);
}

export function Exchange(payload: string, revision: number): $CancellablePromise<string> {
    return $Call.ByID(2064768723, payload, revision);
}

export function ExchangeVault(kind: string, id: string, peer: string, space: string, binding: number): $CancellablePromise<string> {
    return $Call.ByID(858656725, kind, id, peer, space, binding);
}

export function ForkVaultSession(spaceID: string, key: string, ref: string): $CancellablePromise<void> {
    return $Call.ByID(2453123446, spaceID, key, ref);
}

export function Load(): $CancellablePromise<$models.DesktopSyncState> {
    return $Call.ByID(3448827274).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * MarkSynced runs only after every enabled document has completed this round.
 */
export function MarkSynced(spaceID: string, revision: number): $CancellablePromise<void> {
    return $Call.ByID(809034733, spaceID, revision);
}

export function PollAuthorization(): $CancellablePromise<boolean> {
    return $Call.ByID(1058338284);
}

export function PrepareVault(kind: string, id: string): $CancellablePromise<$models.DesktopVaultState> {
    return $Call.ByID(1935779003, kind, id).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * Compare-and-swap protects edits made by another Wails call during network IO.
 */
export function Save(input: $models.DesktopSyncSave): $CancellablePromise<boolean> {
    return $Call.ByID(2416178047, input);
}

export function SaveVault(input: $models.DesktopVaultSave): $CancellablePromise<boolean> {
    return $Call.ByID(236178537, input);
}

export function SessionCandidates(): $CancellablePromise<$models.DesktopSyncCandidate[]> {
    return $Call.ByID(3070277612).then(($result: any) => {
        return $$createType2($result);
    });
}

export function SetEnabled(enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(4084228303, enabled);
}

export function SetScopes(scopes: syncdata$0.SyncScopes): $CancellablePromise<void> {
    return $Call.ByID(4146449951, scopes);
}

export function VaultConflicts(): $CancellablePromise<syncdata$0.VaultConflict[]> {
    return $Call.ByID(3616236021).then(($result: any) => {
        return $$createType6($result);
    });
}

export function VaultList(): $CancellablePromise<$models.DesktopVaultEntry[]> {
    return $Call.ByID(763749834).then(($result: any) => {
        return $$createType8($result);
    });
}

// Private type creation functions
const $$createType0 = $models.DesktopSyncLogin.createFrom;
const $$createType1 = $models.DesktopSyncCandidate.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = $models.DesktopSyncState.createFrom;
const $$createType4 = $models.DesktopVaultState.createFrom;
const $$createType5 = syncdata$0.VaultConflict.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = $models.DesktopVaultEntry.createFrom;
const $$createType8 = $Create.Array($$createType7);
