// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function CheckForUpdate(): $CancellablePromise<$models.DesktopUpdateCheckResult> {
    return $Call.ByID(2029379206).then(($result: any) => {
        return $$createType0($result);
    });
}

export function GetUpdateStatus(): $CancellablePromise<$models.DesktopUpdateCheckResult> {
    return $Call.ByID(3256684119).then(($result: any) => {
        return $$createType0($result);
    });
}

export function InstallUpdate(): $CancellablePromise<$models.DesktopUpdateCheckResult> {
    return $Call.ByID(1351184178).then(($result: any) => {
        return $$createType0($result);
    });
}

export function RestartToUpdate(): $CancellablePromise<void> {
    return $Call.ByID(1561839647);
}

// Private type creation functions
const $$createType0 = $models.DesktopUpdateCheckResult.createFrom;
