// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function ListPreferences(): $CancellablePromise<$models.DesktopPreferenceSnapshot> {
    return $Call.ByID(3443184929).then(($result: any) => {
        return $$createType0($result);
    });
}

export function OpenDataDir(): $CancellablePromise<void> {
    return $Call.ByID(3791649608);
}

export function RemovePreference(key: string): $CancellablePromise<void> {
    return $Call.ByID(164417316, key);
}

export function RuntimeInfo(): $CancellablePromise<$models.DesktopRuntimeInfo> {
    return $Call.ByID(3211740111).then(($result: any) => {
        return $$createType2($result);
    });
}

export function SetPreference(key: string, value: string): $CancellablePromise<void> {
    return $Call.ByID(2713829830, key, value);
}

// Private type creation functions
var $$createType0 = (function $$initCreateType0(...args: any[]): any {
    if ($$createType0 === $$initCreateType0) {
        $$createType0 = $$createType1;
    }
    return $$createType0(...args);
});
const $$createType1 = $Create.Map($Create.Any, $Create.Any);
const $$createType2 = $models.DesktopRuntimeInfo.createFrom;
