// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function Close(input: $models.DesktopTerminalCloseInput): $CancellablePromise<void> {
    return $Call.ByID(2176147339, input);
}

export function Resize(input: $models.DesktopTerminalResizeInput): $CancellablePromise<void> {
    return $Call.ByID(3001817145, input);
}

export function Start(input: $models.DesktopTerminalStartInput): $CancellablePromise<void> {
    return $Call.ByID(1081856935, input);
}

export function Write(input: $models.DesktopTerminalWriteInput): $CancellablePromise<void> {
    return $Call.ByID(822013716, input);
}
