// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function Create(input: $models.DesktopServerInput): $CancellablePromise<$models.DesktopServer> {
    return $Call.ByID(3735879914, input).then(($result: any) => {
        return $$createType0($result);
    });
}

export function Delete(id: string): $CancellablePromise<void> {
    return $Call.ByID(203420633, id);
}

export function DeleteSSHKey(id: number): $CancellablePromise<void> {
    return $Call.ByID(4022397028, id);
}

export function ExecuteCommand(input: $models.DesktopServerCommandInput): $CancellablePromise<$models.DesktopServerCommandResult> {
    return $Call.ByID(3329992570, input).then(($result: any) => {
        return $$createType1($result);
    });
}

export function ExecuteCommandContext(input: $models.DesktopServerCommandInput): $CancellablePromise<$models.DesktopServerCommandResult> {
    return $Call.ByID(3562182085, input).then(($result: any) => {
        return $$createType1($result);
    });
}

export function GetById(id: string): $CancellablePromise<$models.DesktopServer> {
    return $Call.ByID(593733294, id).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * GetStatistics returns filter metadata without loading connection credentials.
 */
export function GetStatistics(): $CancellablePromise<{ [_ in string]?: any }> {
    return $Call.ByID(4179477533).then(($result: any) => {
        return $$createType2($result);
    });
}

export function ImportSSHKey(input: $models.DesktopSSHKeyImport): $CancellablePromise<$models.DesktopSSHKey> {
    return $Call.ByID(2541512058, input).then(($result: any) => {
        return $$createType3($result);
    });
}

export function List(params: $models.DesktopServerListParams): $CancellablePromise<$models.DesktopServerListResult> {
    return $Call.ByID(2124418906, params).then(($result: any) => {
        return $$createType4($result);
    });
}

export function ListSSHKeys(): $CancellablePromise<$models.DesktopSSHKey[]> {
    return $Call.ByID(681221252).then(($result: any) => {
        return $$createType5($result);
    });
}

export function MarkConnected(id: string): $CancellablePromise<$models.DesktopServer> {
    return $Call.ByID(337195074, id).then(($result: any) => {
        return $$createType0($result);
    });
}

export function Reorder(serverIds: string[]): $CancellablePromise<void> {
    return $Call.ByID(2548844453, serverIds);
}

export function Update(id: string, input: $models.DesktopServerInput): $CancellablePromise<$models.DesktopServer> {
    return $Call.ByID(3462321783, id, input).then(($result: any) => {
        return $$createType0($result);
    });
}

// Private type creation functions
const $$createType0 = $models.DesktopServer.createFrom;
const $$createType1 = $models.DesktopServerCommandResult.createFrom;
const $$createType2 = $Create.Map($Create.Any, $Create.Any);
const $$createType3 = $models.DesktopSSHKey.createFrom;
const $$createType4 = $models.DesktopServerListResult.createFrom;
const $$createType5 = $Create.Array($$createType3);
