// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function Create(input: $models.DesktopScriptInput): $CancellablePromise<$models.DesktopScript> {
    return $Call.ByID(3239668854, input).then(($result: any) => {
        return $$createType0($result);
    });
}

export function CreateBatchTask(input: $models.DesktopBatchTaskInput): $CancellablePromise<$models.DesktopBatchTask> {
    return $Call.ByID(3936537999, input).then(($result: any) => {
        return $$createType1($result);
    });
}

export function Delete(id: string): $CancellablePromise<void> {
    return $Call.ByID(3478005373, id);
}

export function Execute(id: string): $CancellablePromise<void> {
    return $Call.ByID(2148586209, id);
}

export function GetBatchTaskById(id: string): $CancellablePromise<$models.DesktopBatchTask> {
    return $Call.ByID(2765301039, id).then(($result: any) => {
        return $$createType1($result);
    });
}

export function GetById(id: string): $CancellablePromise<$models.DesktopScript> {
    return $Call.ByID(2982217386, id).then(($result: any) => {
        return $$createType0($result);
    });
}

export function List(params: $models.DesktopScriptListParams): $CancellablePromise<$models.DesktopScriptListResult> {
    return $Call.ByID(371795774, params).then(($result: any) => {
        return $$createType2($result);
    });
}

export function ListBatchTasks(params: $models.DesktopBatchTaskListParams): $CancellablePromise<$models.DesktopBatchTaskListResult> {
    return $Call.ByID(3540927868, params).then(($result: any) => {
        return $$createType3($result);
    });
}

export function StartBatchTask(id: string): $CancellablePromise<$models.DesktopBatchTaskStartResult> {
    return $Call.ByID(2623776891, id).then(($result: any) => {
        return $$createType4($result);
    });
}

export function Update(id: string, input: $models.DesktopScriptInput): $CancellablePromise<$models.DesktopScript> {
    return $Call.ByID(2685970331, id, input).then(($result: any) => {
        return $$createType0($result);
    });
}

// Private type creation functions
const $$createType0 = $models.DesktopScript.createFrom;
const $$createType1 = $models.DesktopBatchTask.createFrom;
const $$createType2 = $models.DesktopScriptListResult.createFrom;
const $$createType3 = $models.DesktopBatchTaskListResult.createFrom;
const $$createType4 = $models.DesktopBatchTaskStartResult.createFrom;
