// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function ClearUpdateFailureNotice(): $CancellablePromise<void> {
    return $Call.ByID(2044166355);
}

export function GetUpdateFailureNotice(): $CancellablePromise<$models.DesktopUpdateFailureNotice | null> {
    return $Call.ByID(3842279080).then(($result: any) => {
        return $$createType1($result);
    });
}

export function ListPreferences(): $CancellablePromise<$models.DesktopPreferenceSnapshot> {
    return $Call.ByID(3443184929).then(($result: any) => {
        return $$createType2($result);
    });
}

export function OpenDataDir(): $CancellablePromise<void> {
    return $Call.ByID(3791649608);
}

export function OpenPathInFileManager(path: string): $CancellablePromise<void> {
    return $Call.ByID(2478855450, path);
}

export function RemovePreference(key: string): $CancellablePromise<void> {
    return $Call.ByID(164417316, key);
}

export function RuntimeInfo(): $CancellablePromise<$models.DesktopRuntimeInfo> {
    return $Call.ByID(3211740111).then(($result: any) => {
        return $$createType4($result);
    });
}

export function SetPreference(key: string, value: string): $CancellablePromise<void> {
    return $Call.ByID(2713829830, key, value);
}

// Private type creation functions
const $$createType0 = $models.DesktopUpdateFailureNotice.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
var $$createType2 = (function $$initCreateType2(...args: any[]): any {
    if ($$createType2 === $$initCreateType2) {
        $$createType2 = $$createType3;
    }
    return $$createType2(...args);
});
const $$createType3 = $Create.Map($Create.Any, $Create.Any);
const $$createType4 = $models.DesktopRuntimeInfo.createFrom;
