// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function Authenticate(input: $models.DesktopSFTPAuthenticateInput): $CancellablePromise<void> {
    return $Call.ByID(1027935973, input);
}

export function BatchDelete(input: $models.DesktopSFTPBatchDeleteInput): $CancellablePromise<$models.DesktopSFTPBatchDeleteResult> {
    return $Call.ByID(4063668539, input).then(($result: any) => {
        return $$createType0($result);
    });
}

export function BatchDownload(input: $models.DesktopSFTPBatchDownloadInput): $CancellablePromise<void> {
    return $Call.ByID(4273010992, input);
}

export function CancelTransfer($0: string): $CancellablePromise<void> {
    return $Call.ByID(3900337609, $0);
}

export function CancelUploadTask($0: string): $CancellablePromise<void> {
    return $Call.ByID(2976517630, $0);
}

export function Chmod(input: $models.DesktopSFTPChmodInput): $CancellablePromise<void> {
    return $Call.ByID(2779146953, input);
}

export function CloseConnection(serverID: string): $CancellablePromise<void> {
    return $Call.ByID(1389952524, serverID);
}

export function CreateDirectory(input: $models.DesktopSFTPPathInput): $CancellablePromise<$models.DesktopSFTPFileInfo> {
    return $Call.ByID(1742580663, input).then(($result: any) => {
        return $$createType1($result);
    });
}

export function CreateUploadTask(): $CancellablePromise<{ [_ in string]?: string }> {
    return $Call.ByID(1482468324).then(($result: any) => {
        return $$createType2($result);
    });
}

export function Delete(input: $models.DesktopSFTPPathInput): $CancellablePromise<$models.DesktopSFTPFileInfo> {
    return $Call.ByID(116437395, input).then(($result: any) => {
        return $$createType1($result);
    });
}

export function DirectTransfer(input: $models.DesktopSFTPDirectTransferInput): $CancellablePromise<$models.DesktopSFTPDirectTransferResult> {
    return $Call.ByID(3508449626, input).then(($result: any) => {
        return $$createType3($result);
    });
}

export function DownloadFile(input: $models.DesktopSFTPDownloadFileInput): $CancellablePromise<void> {
    return $Call.ByID(2953817614, input);
}

export function GetDiskUsage(input: $models.DesktopSFTPPathInput): $CancellablePromise<$models.DesktopSFTPDiskUsageResult> {
    return $Call.ByID(3684496188, input).then(($result: any) => {
        return $$createType6($result);
    });
}

export function GetFileInfo(input: $models.DesktopSFTPPathInput): $CancellablePromise<$models.DesktopSFTPFileInfo> {
    return $Call.ByID(4074473146, input).then(($result: any) => {
        return $$createType1($result);
    });
}

export function GetUploadTask($0: string): $CancellablePromise<$models.DesktopSFTPUploadTaskStatus> {
    return $Call.ByID(1928740572, $0).then(($result: any) => {
        return $$createType7($result);
    });
}

export function GetTransferTask($0: string): $CancellablePromise<$models.DesktopSFTPUploadTaskStatus> {
    return $Call.ByID(2480019214, $0).then(($result: any) => {
        return $$createType7($result);
    });
}

export function ListDirectory(input: $models.DesktopSFTPPathInput): $CancellablePromise<$models.DesktopSFTPDirectoryListResult> {
    return $Call.ByID(3642171603, input).then(($result: any) => {
        return $$createType4($result);
    });
}

export function ListUploadTasks(): $CancellablePromise<$models.DesktopSFTPUploadTaskListResult> {
    return $Call.ByID(1257542041).then(($result: any) => {
        return $$createType5($result);
    });
}

export function ReadFile(input: $models.DesktopSFTPPathInput): $CancellablePromise<string> {
    return $Call.ByID(1777379530, input);
}

export function Rename(input: $models.DesktopSFTPRenameInput): $CancellablePromise<$models.DesktopSFTPFileInfo> {
    return $Call.ByID(1192695914, input).then(($result: any) => {
        return $$createType1($result);
    });
}

export function UploadFile(input: $models.DesktopSFTPUploadFileInput): $CancellablePromise<$models.DesktopSFTPFileInfo> {
    return $Call.ByID(796206687, input).then(($result: any) => {
        return $$createType1($result);
    });
}

export function WriteFile(input: $models.DesktopSFTPWriteFileInput): $CancellablePromise<$models.DesktopSFTPFileInfo> {
    return $Call.ByID(4109382121, input).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = $models.DesktopSFTPBatchDeleteResult.createFrom;
const $$createType1 = $models.DesktopSFTPFileInfo.createFrom;
const $$createType2 = $Create.Map($Create.Any, $Create.Any);
const $$createType3 = $models.DesktopSFTPDirectTransferResult.createFrom;
const $$createType4 = $models.DesktopSFTPDirectoryListResult.createFrom;
const $$createType5 = $models.DesktopSFTPUploadTaskListResult.createFrom;
const $$createType6 = $models.DesktopSFTPDiskUsageResult.createFrom;
const $$createType7 = $models.DesktopSFTPUploadTaskStatus.createFrom;
