// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function Cancel(id: string): $CancellablePromise<$models.DesktopTaskRun> {
    return $Call.ByID(1045195030, id).then(($result: any) => {
        return $$createType0($result);
    });
}

export function Cleanup(retentionDays: number): $CancellablePromise<$models.DesktopTaskCleanupResult> {
    return $Call.ByID(3833806232, retentionDays).then(($result: any) => {
        return $$createType1($result);
    });
}

export function Get(id: string): $CancellablePromise<$models.DesktopTaskDetails> {
    return $Call.ByID(838275312, id).then(($result: any) => {
        return $$createType2($result);
    });
}

export function List(input: $models.DesktopTaskListInput): $CancellablePromise<$models.DesktopTaskRunList> {
    return $Call.ByID(3341406556, input).then(($result: any) => {
        return $$createType3($result);
    });
}

export function Retry(id: string): $CancellablePromise<{ [_ in string]?: string }> {
    return $Call.ByID(1672711422, id).then(($result: any) => {
        return $$createType4($result);
    });
}

export function Statistics(): $CancellablePromise<$models.DesktopTaskStatistics> {
    return $Call.ByID(714695431).then(($result: any) => {
        return $$createType5($result);
    });
}

// Private type creation functions
const $$createType0 = $models.DesktopTaskRun.createFrom;
const $$createType1 = $models.DesktopTaskCleanupResult.createFrom;
const $$createType2 = $models.DesktopTaskDetails.createFrom;
const $$createType3 = $models.DesktopTaskRunList.createFrom;
const $$createType4 = $Create.Map($Create.Any, $Create.Any);
const $$createType5 = $models.DesktopTaskStatistics.createFrom;
