// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function Delete(id: string): $CancellablePromise<void> {
    return $Call.ByID(3175392549, id);
}

export function List(limit: number): $CancellablePromise<$models.DesktopNotificationList> {
    return $Call.ByID(1345266454, limit).then(($result: any) => {
        return $$createType0($result);
    });
}

export function MarkAllRead(): $CancellablePromise<void> {
    return $Call.ByID(2316758110);
}

export function MarkRead(id: string): $CancellablePromise<void> {
    return $Call.ByID(107837639, id);
}

export function Publish(eventType: string, severity: string, title: string, message: string, actionURL: string): $CancellablePromise<void> {
    return $Call.ByID(3893119697, eventType, severity, title, message, actionURL);
}

// Private type creation functions
const $$createType0 = $models.DesktopNotificationList.createFrom;
