// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function CancelSession(id: string): $CancellablePromise<{ [_ in string]?: boolean }> {
    return $Call.ByID(3028493811, id).then(($result: any) => {
        return $$createType0($result);
    });
}

export function CloseSession(id: string): $CancellablePromise<void> {
    return $Call.ByID(2012466751, id);
}

export function ConfirmTask(input: $models.DesktopAIConfirmTaskInput): $CancellablePromise<$models.DesktopAICreateSessionResponse> {
    return $Call.ByID(1018369184, input).then(($result: any) => {
        return $$createType1($result);
    });
}

export function CreateSession(input: $models.DesktopAICreateSessionInput): $CancellablePromise<$models.DesktopAICreateSessionResponse> {
    return $Call.ByID(1223357961, input).then(($result: any) => {
        return $$createType1($result);
    });
}

export function DeleteMessage(sessionID: string, messageID: string): $CancellablePromise<$models.DesktopAICreateSessionResponse> {
    return $Call.ByID(2510145091, sessionID, messageID).then(($result: any) => {
        return $$createType1($result);
    });
}

export function DeleteSession(id: string): $CancellablePromise<void> {
    return $Call.ByID(374287456, id);
}

export function GetAIConfig(): $CancellablePromise<$models.DesktopAIConfigStatus> {
    return $Call.ByID(3332758201).then(($result: any) => {
        return $$createType2($result);
    });
}

export function GetLatestSession(scope: $models.DesktopAISessionScope | null): $CancellablePromise<$models.DesktopAICreateSessionResponse | null> {
    return $Call.ByID(2690707750, scope).then(($result: any) => {
        return $$createType3($result);
    });
}

export function GetSession(id: string): $CancellablePromise<$models.DesktopAICreateSessionResponse> {
    return $Call.ByID(232960739, id).then(($result: any) => {
        return $$createType1($result);
    });
}

export function GetUserAIConfig(): $CancellablePromise<$models.DesktopUserAIConfig> {
    return $Call.ByID(2043053706).then(($result: any) => {
        return $$createType4($result);
    });
}

export function ListSessions(params: $models.DesktopAIListSessionsParams): $CancellablePromise<$models.DesktopAIListSessionsResult> {
    return $Call.ByID(1081193070, params).then(($result: any) => {
        return $$createType5($result);
    });
}

export function RegenerateMessage(input: $models.DesktopAIRegenerateMessageInput): $CancellablePromise<$models.DesktopAICreateSessionResponse> {
    return $Call.ByID(3319367080, input).then(($result: any) => {
        return $$createType1($result);
    });
}

export function RenameSession(id: string, title: string): $CancellablePromise<{ [_ in string]?: boolean }> {
    return $Call.ByID(362709311, id, title).then(($result: any) => {
        return $$createType0($result);
    });
}

export function SaveUserAIConfig(input: $models.DesktopSaveUserAIConfigRequest): $CancellablePromise<void> {
    return $Call.ByID(2363833453, input);
}

export function SendMessage(input: $models.DesktopAISendMessageInput): $CancellablePromise<$models.DesktopAICreateSessionResponse> {
    return $Call.ByID(256307000, input).then(($result: any) => {
        return $$createType1($result);
    });
}

export function UpdateMessage(input: $models.DesktopAIUpdateMessageInput): $CancellablePromise<$models.DesktopAICreateSessionResponse> {
    return $Call.ByID(498586565, input).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = $models.DesktopAICreateSessionResponse.createFrom;
const $$createType2 = $models.DesktopAIConfigStatus.createFrom;
const $$createType3 = $Create.Nullable($$createType1);
const $$createType4 = $models.DesktopUserAIConfig.createFrom;
const $$createType5 = $models.DesktopAIListSessionsResult.createFrom;
