// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function ExportBackup(input: $models.DesktopBackupExportInput): $CancellablePromise<$models.DesktopBackupExportResult> {
    return $Call.ByID(1621194995, input).then(($result: any) => {
        return $$createType0($result);
    });
}

export function RestoreBackup(input: $models.DesktopBackupRestoreInput): $CancellablePromise<$models.DesktopBackupRestoreResult> {
    return $Call.ByID(3388571433, input).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = $models.DesktopBackupExportResult.createFrom;
const $$createType1 = $models.DesktopBackupRestoreResult.createFrom;
