// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function Collect(input: $models.DesktopMonitorCollectInput): $CancellablePromise<$models.DesktopMonitorSnapshot> {
    return $Call.ByID(311523927, input).then(($result: any) => {
        return $$createType0($result);
    });
}

export function CollectContext(input: $models.DesktopMonitorCollectInput): $CancellablePromise<$models.DesktopMonitorSnapshot> {
    return $Call.ByID(498304254, input).then(($result: any) => {
        return $$createType0($result);
    });
}

// Private type creation functions
const $$createType0 = $models.DesktopMonitorSnapshot.createFrom;
