// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as ActivityLogService from "./activitylogservice.js";
import * as DesktopServerService from "./desktopserverservice.js";
import * as DesktopService from "./desktopservice.js";
export {
    ActivityLogService,
    DesktopServerService,
    DesktopService
};

export {
    DesktopActivityLogItem,
    DesktopActivityLogListParams,
    DesktopActivityLogListResult,
    DesktopActivityLogRecordInput,
    DesktopActivityLogStatistics,
    DesktopActivityLogStatus,
    DesktopRuntimeInfo,
    DesktopServer,
    DesktopServerAuthMethod,
    DesktopServerCommandInput,
    DesktopServerCommandResult,
    DesktopServerInput,
    DesktopServerListParams,
    DesktopServerListResult,
    DesktopServerStatus
} from "./models.js";

export type {
    DesktopCapability
} from "./models.js";
