// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as ActivityLogService from "./activitylogservice.js";
import * as DesktopAIService from "./desktopaiservice.js";
import * as DesktopBackupService from "./desktopbackupservice.js";
import * as DesktopDockerService from "./desktopdockerservice.js";
import * as DesktopGateway from "./desktopgateway.js";
import * as DesktopMonitorService from "./desktopmonitorservice.js";
import * as DesktopSFTPService from "./desktopsftpservice.js";
import * as DesktopScriptService from "./desktopscriptservice.js";
import * as DesktopServerService from "./desktopserverservice.js";
import * as DesktopService from "./desktopservice.js";
import * as DesktopTerminalService from "./desktopterminalservice.js";
import * as DesktopUpdateService from "./desktopupdateservice.js";
export {
    ActivityLogService,
    DesktopAIService,
    DesktopBackupService,
    DesktopDockerService,
    DesktopGateway,
    DesktopMonitorService,
    DesktopSFTPService,
    DesktopScriptService,
    DesktopServerService,
    DesktopService,
    DesktopTerminalService,
    DesktopUpdateService
};

export {
    DesktopAIConfigStatus,
    DesktopAICreateSessionInput,
    DesktopAICreateSessionResponse,
    DesktopAIListSessionsParams,
    DesktopAIListSessionsResult,
    DesktopAIMessageView,
    DesktopAIPermissionMode,
    DesktopAISendMessageInput,
    DesktopAISessionListItem,
    DesktopAISessionScope,
    DesktopAISessionStatus,
    DesktopAISessionView,
    DesktopAITaskView,
    DesktopAIToolView,
    DesktopActivityLogItem,
    DesktopActivityLogListParams,
    DesktopActivityLogListResult,
    DesktopActivityLogRecordInput,
    DesktopActivityLogStatistics,
    DesktopActivityLogStatus,
    DesktopBackupExportInput,
    DesktopBackupExportResult,
    DesktopBackupRestoreInput,
    DesktopBackupRestoreResult,
    DesktopBatchTask,
    DesktopBatchTaskInput,
    DesktopBatchTaskListParams,
    DesktopBatchTaskListResult,
    DesktopBatchTaskStartResult,
    DesktopDockerContainer,
    DesktopDockerContainerInput,
    DesktopDockerContainerLogsInput,
    DesktopDockerContainerLogsResult,
    DesktopDockerContainerStats,
    DesktopDockerContainersResult,
    DesktopDockerImage,
    DesktopDockerImageUpdateCheckResult,
    DesktopDockerImagesResult,
    DesktopDockerListContainersInput,
    DesktopDockerMount,
    DesktopDockerPort,
    DesktopDockerRemoveContainerInput,
    DesktopDockerResourcesResult,
    DesktopDockerServerInput,
    DesktopDockerSystemInfo,
    DesktopGatewayInfo,
    DesktopMonitorCPUInfo,
    DesktopMonitorCollectInput,
    DesktopMonitorDiskInfo,
    DesktopMonitorDockerInfo,
    DesktopMonitorMemoryInfo,
    DesktopMonitorNetworkInfo,
    DesktopMonitorSnapshot,
    DesktopMonitorSystemInfo,
    DesktopRuntimeInfo,
    DesktopSFTPAuthenticateInput,
    DesktopSFTPBatchDeleteInput,
    DesktopSFTPBatchDeleteResult,
    DesktopSFTPBatchDownloadInput,
    DesktopSFTPBatchOperationError,
    DesktopSFTPChmodInput,
    DesktopSFTPDirectTransferInput,
    DesktopSFTPDirectTransferResult,
    DesktopSFTPDirectoryListResult,
    DesktopSFTPDownloadFileInput,
    DesktopSFTPFileInfo,
    DesktopSFTPPathInput,
    DesktopSFTPRenameInput,
    DesktopSFTPUploadFileInput,
    DesktopSFTPUploadTaskListResult,
    DesktopSFTPUploadTaskStatus,
    DesktopSFTPWriteFileInput,
    DesktopSSHCredential,
    DesktopSaveUserAIConfigRequest,
    DesktopScript,
    DesktopScriptInput,
    DesktopScriptListParams,
    DesktopScriptListResult,
    DesktopServer,
    DesktopServerAuthMethod,
    DesktopServerCommandInput,
    DesktopServerCommandResult,
    DesktopServerInput,
    DesktopServerListParams,
    DesktopServerListResult,
    DesktopServerStatus,
    DesktopTerminalCloseInput,
    DesktopTerminalPingInput,
    DesktopTerminalPingResult,
    DesktopTerminalResizeInput,
    DesktopTerminalStartInput,
    DesktopTerminalWriteInput,
    DesktopUpdateAsset,
    DesktopUpdateCheckResult,
    DesktopUpdateStatus,
    DesktopUserAIConfig
} from "./models.js";

export type {
    DesktopAITaskStatus,
    DesktopCapability,
    DesktopPreferenceSnapshot
} from "./models.js";
