// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class DesktopAIConfigStatus {
    "configured": boolean;
    "provider"?: string;
    "model"?: string;
    "models"?: string[];
    "has_key": boolean;
    "message"?: string;

    /** Creates a new DesktopAIConfigStatus instance. */
    constructor($$source: Partial<DesktopAIConfigStatus> = {}) {
        if (!("configured" in $$source)) {
            this["configured"] = false;
        }
        if (!("has_key" in $$source)) {
            this["has_key"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DesktopAIConfigStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): DesktopAIConfigStatus {
        const $$createField3_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("models" in $$parsedSource) {
            $$parsedSource["models"] = $$createField3_0($$parsedSource["models"]);
        }
        return new DesktopAIConfigStatus($$parsedSource as Partial<DesktopAIConfigStatus>);
    }
}

export class DesktopAICreateSessionInput {
    "model"?: string;
    "permission_mode"?: DesktopAIPermissionMode;
    "scope"?: DesktopAISessionScope | null;

    /** Creates a new DesktopAICreateSessionInput instance. */
    constructor($$source: Partial<DesktopAICreateSessionInput> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DesktopAICreateSessionInput instance from a string or object.
     */
    static createFrom($$source: any = {}): DesktopAICreateSessionInput {
        const $$createField2_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("scope" in $$parsedSource) {
            $$parsedSource["scope"] = $$createField2_0($$parsedSource["scope"]);
        }
        return new DesktopAICreateSessionInput($$parsedSource as Partial<DesktopAICreateSessionInput>);
    }
}

export class DesktopAICreateSessionResponse {
    "session_id": string;
    "session": DesktopAISessionView;
    "default_transport": string;

    /** Creates a new DesktopAICreateSessionResponse instance. */
    constructor($$source: Partial<DesktopAICreateSessionResponse> = {}) {
        if (!("session_id" in $$source)) {
            this["session_id"] = "";
        }
        if (!("session" in $$source)) {
            this["session"] = (new DesktopAISessionView());
        }
        if (!("default_transport" in $$source)) {
            this["default_transport"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DesktopAICreateSessionResponse instance from a string or object.
     */
    static createFrom($$source: any = {}): DesktopAICreateSessionResponse {
        const $$createField1_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("session" in $$parsedSource) {
            $$parsedSource["session"] = $$createField1_0($$parsedSource["session"]);
        }
        return new DesktopAICreateSessionResponse($$parsedSource as Partial<DesktopAICreateSessionResponse>);
    }
}

export class DesktopAIListSessionsParams {
    "page"?: number;
    "limit"?: number;
    "q"?: string;
    "scope_kind"?: string;
    "terminal_session_id"?: string;
    "server_id"?: string;

    /** Creates a new DesktopAIListSessionsParams instance. */
    constructor($$source: Partial<DesktopAIListSessionsParams> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DesktopAIListSessionsParams instance from a string or object.
     */
    static createFrom($$source: any = {}): DesktopAIListSessionsParams {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DesktopAIListSessionsParams($$parsedSource as Partial<DesktopAIListSessionsParams>);
    }
}

export class DesktopAIListSessionsResult {
    "items": DesktopAISessionListItem[];
    "total": number;

    /** Creates a new DesktopAIListSessionsResult instance. */
    constructor($$source: Partial<DesktopAIListSessionsResult> = {}) {
        if (!("items" in $$source)) {
            this["items"] = [];
        }
        if (!("total" in $$source)) {
            this["total"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DesktopAIListSessionsResult instance from a string or object.
     */
    static createFrom($$source: any = {}): DesktopAIListSessionsResult {
        const $$createField0_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("items" in $$parsedSource) {
            $$parsedSource["items"] = $$createField0_0($$parsedSource["items"]);
        }
        return new DesktopAIListSessionsResult($$parsedSource as Partial<DesktopAIListSessionsResult>);
    }
}

export class DesktopAIMessageView {
    "id": string;
    "role": string;
    "content": string;
    "created_at": string;

    /** Creates a new DesktopAIMessageView instance. */
    constructor($$source: Partial<DesktopAIMessageView> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("role" in $$source)) {
            this["role"] = "";
        }
        if (!("content" in $$source)) {
            this["content"] = "";
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DesktopAIMessageView instance from a string or object.
     */
    static createFrom($$source: any = {}): DesktopAIMessageView {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DesktopAIMessageView($$parsedSource as Partial<DesktopAIMessageView>);
    }
}

export enum DesktopAIPermissionMode {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    DesktopAIPermissionReadonly = "readonly",
    DesktopAIPermissionBalanced = "balanced",
    DesktopAIPermissionPrivileged = "privileged",
};

export class DesktopAISendMessageInput {
    "session_id": string;
    "content": string;
    "context"?: string;
    "model"?: string;
    "permission_mode"?: DesktopAIPermissionMode;
    "scope"?: DesktopAISessionScope | null;

    /** Creates a new DesktopAISendMessageInput instance. */
    constructor($$source: Partial<DesktopAISendMessageInput> = {}) {
        if (!("session_id" in $$source)) {
            this["session_id"] = "";
        }
        if (!("content" in $$source)) {
            this["content"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DesktopAISendMessageInput instance from a string or object.
     */
    static createFrom($$source: any = {}): DesktopAISendMessageInput {
        const $$createField5_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("scope" in $$parsedSource) {
            $$parsedSource["scope"] = $$createField5_0($$parsedSource["scope"]);
        }
        return new DesktopAISendMessageInput($$parsedSource as Partial<DesktopAISendMessageInput>);
    }
}

export class DesktopAISessionListItem {
    "id": string;
    "model": string;
    "permission_mode": DesktopAIPermissionMode;
    "status": DesktopAISessionStatus;
    "title": string;
    "custom_title": boolean;
    "message_count": number;
    "task_count": number;
    "created_at": string;
    "updated_at": string;

    /** Creates a new DesktopAISessionListItem instance. */
    constructor($$source: Partial<DesktopAISessionListItem> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("model" in $$source)) {
            this["model"] = "";
        }
        if (!("permission_mode" in $$source)) {
            this["permission_mode"] = DesktopAIPermissionMode.$zero;
        }
        if (!("status" in $$source)) {
            this["status"] = DesktopAISessionStatus.$zero;
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("custom_title" in $$source)) {
            this["custom_title"] = false;
        }
        if (!("message_count" in $$source)) {
            this["message_count"] = 0;
        }
        if (!("task_count" in $$source)) {
            this["task_count"] = 0;
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = "";
        }
        if (!("updated_at" in $$source)) {
            this["updated_at"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DesktopAISessionListItem instance from a string or object.
     */
    static createFrom($$source: any = {}): DesktopAISessionListItem {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DesktopAISessionListItem($$parsedSource as Partial<DesktopAISessionListItem>);
    }
}

export class DesktopAISessionScope {
    "kind"?: string;
    "terminal_session_id"?: string;
    "server_id"?: string;
    "server_name"?: string;
    "host"?: string;
    "port"?: number;
    "username"?: string;

    /** Creates a new DesktopAISessionScope instance. */
    constructor($$source: Partial<DesktopAISessionScope> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DesktopAISessionScope instance from a string or object.
     */
    static createFrom($$source: any = {}): DesktopAISessionScope {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DesktopAISessionScope($$parsedSource as Partial<DesktopAISessionScope>);
    }
}

export enum DesktopAISessionStatus {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    DesktopAISessionIdle = "idle",
    DesktopAISessionRunning = "running",
    DesktopAISessionClosed = "closed",
};

export class DesktopAISessionView {
    "id": string;
    "model": string;
    "permission_mode": DesktopAIPermissionMode;
    "scope"?: DesktopAISessionScope | null;
    "status": DesktopAISessionStatus;
    "created_at": string;
    "updated_at": string;
    "messages": DesktopAIMessageView[];
    "tasks": DesktopAITaskView[];
    "ui_messages": { [_ in string]?: any }[];
    "available_tools": DesktopAIToolView[];
    "default_transport": string;

    /** Creates a new DesktopAISessionView instance. */
    constructor($$source: Partial<DesktopAISessionView> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("model" in $$source)) {
            this["model"] = "";
        }
        if (!("permission_mode" in $$source)) {
            this["permission_mode"] = DesktopAIPermissionMode.$zero;
        }
        if (!("status" in $$source)) {
            this["status"] = DesktopAISessionStatus.$zero;
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = "";
        }
        if (!("updated_at" in $$source)) {
            this["updated_at"] = "";
        }
        if (!("messages" in $$source)) {
            this["messages"] = [];
        }
        if (!("tasks" in $$source)) {
            this["tasks"] = [];
        }
        if (!("ui_messages" in $$source)) {
            this["ui_messages"] = [];
        }
        if (!("available_tools" in $$source)) {
            this["available_tools"] = [];
        }
        if (!("default_transport" in $$source)) {
            this["default_transport"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DesktopAISessionView instance from a string or object.
     */
    static createFrom($$source: any = {}): DesktopAISessionView {
        const $$createField3_0 = $$createType2;
        const $$createField7_0 = $$createType7;
        const $$createField8_0 = $$createType9;
        const $$createField9_0 = $$createType11;
        const $$createField10_0 = $$createType13;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("scope" in $$parsedSource) {
            $$parsedSource["scope"] = $$createField3_0($$parsedSource["scope"]);
        }
        if ("messages" in $$parsedSource) {
            $$parsedSource["messages"] = $$createField7_0($$parsedSource["messages"]);
        }
        if ("tasks" in $$parsedSource) {
            $$parsedSource["tasks"] = $$createField8_0($$parsedSource["tasks"]);
        }
        if ("ui_messages" in $$parsedSource) {
            $$parsedSource["ui_messages"] = $$createField9_0($$parsedSource["ui_messages"]);
        }
        if ("available_tools" in $$parsedSource) {
            $$parsedSource["available_tools"] = $$createField10_0($$parsedSource["available_tools"]);
        }
        return new DesktopAISessionView($$parsedSource as Partial<DesktopAISessionView>);
    }
}

export type DesktopAITaskStatus = string;

export class DesktopAITaskView {
    "id": string;
    "tool_call_id": string;
    "tool_name": string;
    "tool_display_name"?: string;
    "summary"?: string;
    "status": DesktopAITaskStatus;
    "dangerous": boolean;
    "requires_confirmation": boolean;
    "arguments"?: { [_ in string]?: any };
    "result"?: string;
    "error"?: string;
    "created_at": string;
    "updated_at": string;
    "custom_title"?: boolean;

    /** Creates a new DesktopAITaskView instance. */
    constructor($$source: Partial<DesktopAITaskView> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("tool_call_id" in $$source)) {
            this["tool_call_id"] = "";
        }
        if (!("tool_name" in $$source)) {
            this["tool_name"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("dangerous" in $$source)) {
            this["dangerous"] = false;
        }
        if (!("requires_confirmation" in $$source)) {
            this["requires_confirmation"] = false;
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = "";
        }
        if (!("updated_at" in $$source)) {
            this["updated_at"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DesktopAITaskView instance from a string or object.
     */
    static createFrom($$source: any = {}): DesktopAITaskView {
        const $$createField8_0 = $$createType10;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("arguments" in $$parsedSource) {
            $$parsedSource["arguments"] = $$createField8_0($$parsedSource["arguments"]);
        }
        return new DesktopAITaskView($$parsedSource as Partial<DesktopAITaskView>);
    }
}

export class DesktopAIToolView {
    "name": string;
    "display_name"?: string;
    "description": string;
    "dangerous": boolean;

    /** Creates a new DesktopAIToolView instance. */
    constructor($$source: Partial<DesktopAIToolView> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("dangerous" in $$source)) {
            this["dangerous"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DesktopAIToolView instance from a string or object.
     */
    static createFrom($$source: any = {}): DesktopAIToolView {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DesktopAIToolView($$parsedSource as Partial<DesktopAIToolView>);
    }
}

export class DesktopActivityLogItem {
    "id": string;
    "action": string;
    "resource": string;
    "status": DesktopActivityLogStatus;
    "serverId"?: string;
    "durationMs"?: number;
    "detail"?: string;
    "createdAt": string;

    /** Creates a new DesktopActivityLogItem instance. */
    constructor($$source: Partial<DesktopActivityLogItem> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("action" in $$source)) {
            this["action"] = "";
        }
        if (!("resource" in $$source)) {
            this["resource"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = DesktopActivityLogStatus.$zero;
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DesktopActivityLogItem instance from a string or object.
     */
    static createFrom($$source: any = {}): DesktopActivityLogItem {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DesktopActivityLogItem($$parsedSource as Partial<DesktopActivityLogItem>);
    }
}

export class DesktopActivityLogListParams {
    "page"?: number;
    "limit"?: number;
    "action"?: string;
    "serverId"?: string;
    "status"?: DesktopActivityLogStatus;
    "startDate"?: string;
    "endDate"?: string;

    /** Creates a new DesktopActivityLogListParams instance. */
    constructor($$source: Partial<DesktopActivityLogListParams> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DesktopActivityLogListParams instance from a string or object.
     */
    static createFrom($$source: any = {}): DesktopActivityLogListParams {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DesktopActivityLogListParams($$parsedSource as Partial<DesktopActivityLogListParams>);
    }
}

export class DesktopActivityLogListResult {
    "items": DesktopActivityLogItem[];
    "total": number;
    "page": number;
    "pageSize": number;
    "totalPages": number;

    /** Creates a new DesktopActivityLogListResult instance. */
    constructor($$source: Partial<DesktopActivityLogListResult> = {}) {
        if (!("items" in $$source)) {
            this["items"] = [];
        }
        if (!("total" in $$source)) {
            this["total"] = 0;
        }
        if (!("page" in $$source)) {
            this["page"] = 0;
        }
        if (!("pageSize" in $$source)) {
            this["pageSize"] = 0;
        }
        if (!("totalPages" in $$source)) {
            this["totalPages"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DesktopActivityLogListResult instance from a string or object.
     */
    static createFrom($$source: any = {}): DesktopActivityLogListResult {
        const $$createField0_0 = $$createType15;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("items" in $$parsedSource) {
            $$parsedSource["items"] = $$createField0_0($$parsedSource["items"]);
        }
        return new DesktopActivityLogListResult($$parsedSource as Partial<DesktopActivityLogListResult>);
    }
}

export class DesktopActivityLogRecordInput {
    "action": string;
    "resource": string;
    "status": DesktopActivityLogStatus;
    "serverId"?: string;
    "durationMs"?: number;
    "detail"?: string;

    /** Creates a new DesktopActivityLogRecordInput instance. */
    constructor($$source: Partial<DesktopActivityLogRecordInput> = {}) {
        if (!("action" in $$source)) {
            this["action"] = "";
        }
        if (!("resource" in $$source)) {
            this["resource"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = DesktopActivityLogStatus.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DesktopActivityLogRecordInput instance from a string or object.
     */
    static createFrom($$source: any = {}): DesktopActivityLogRecordInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DesktopActivityLogRecordInput($$parsedSource as Partial<DesktopActivityLogRecordInput>);
    }
}

export class DesktopActivityLogStatistics {
    "total": number;
    "successCount": number;
    "failureCount": number;
    "byAction": { [_ in string]?: number };

    /** Creates a new DesktopActivityLogStatistics instance. */
    constructor($$source: Partial<DesktopActivityLogStatistics> = {}) {
        if (!("total" in $$source)) {
            this["total"] = 0;
        }
        if (!("successCount" in $$source)) {
            this["successCount"] = 0;
        }
        if (!("failureCount" in $$source)) {
            this["failureCount"] = 0;
        }
        if (!("byAction" in $$source)) {
            this["byAction"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DesktopActivityLogStatistics instance from a string or object.
     */
    static createFrom($$source: any = {}): DesktopActivityLogStatistics {
        const $$createField3_0 = $$createType16;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("byAction" in $$parsedSource) {
            $$parsedSource["byAction"] = $$createField3_0($$parsedSource["byAction"]);
        }
        return new DesktopActivityLogStatistics($$parsedSource as Partial<DesktopActivityLogStatistics>);
    }
}

export enum DesktopActivityLogStatus {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    DesktopActivityLogSuccess = "success",
    DesktopActivityLogFailure = "failure",
    DesktopActivityLogWarning = "warning",
};

export type DesktopCapability = string;

export type DesktopPreferenceSnapshot = { [_ in string]?: string };

export class DesktopRuntimeInfo {
    "profile": string;
    "version": string;
    "platform": string;
    "arch": string;
    "dataDir": string;
    "capabilities": { [_ in DesktopCapability]?: boolean };

    /** Creates a new DesktopRuntimeInfo instance. */
    constructor($$source: Partial<DesktopRuntimeInfo> = {}) {
        if (!("profile" in $$source)) {
            this["profile"] = "";
        }
        if (!("version" in $$source)) {
            this["version"] = "";
        }
        if (!("platform" in $$source)) {
            this["platform"] = "";
        }
        if (!("arch" in $$source)) {
            this["arch"] = "";
        }
        if (!("dataDir" in $$source)) {
            this["dataDir"] = "";
        }
        if (!("capabilities" in $$source)) {
            this["capabilities"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DesktopRuntimeInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): DesktopRuntimeInfo {
        const $$createField5_0 = $$createType17;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("capabilities" in $$parsedSource) {
            $$parsedSource["capabilities"] = $$createField5_0($$parsedSource["capabilities"]);
        }
        return new DesktopRuntimeInfo($$parsedSource as Partial<DesktopRuntimeInfo>);
    }
}

export class DesktopSaveUserAIConfigRequest {
    "use_system_config": boolean;
    "custom_enabled": boolean;
    "custom_provider": string;
    "custom_api_key": string;
    "custom_endpoint": string;
    "custom_models": string;

    /** Creates a new DesktopSaveUserAIConfigRequest instance. */
    constructor($$source: Partial<DesktopSaveUserAIConfigRequest> = {}) {
        if (!("use_system_config" in $$source)) {
            this["use_system_config"] = false;
        }
        if (!("custom_enabled" in $$source)) {
            this["custom_enabled"] = false;
        }
        if (!("custom_provider" in $$source)) {
            this["custom_provider"] = "";
        }
        if (!("custom_api_key" in $$source)) {
            this["custom_api_key"] = "";
        }
        if (!("custom_endpoint" in $$source)) {
            this["custom_endpoint"] = "";
        }
        if (!("custom_models" in $$source)) {
            this["custom_models"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DesktopSaveUserAIConfigRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): DesktopSaveUserAIConfigRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DesktopSaveUserAIConfigRequest($$parsedSource as Partial<DesktopSaveUserAIConfigRequest>);
    }
}

export class DesktopServer {
    "id": string;
    "user_id": string;
    "name"?: string;
    "host": string;
    "port": number;
    "username": string;
    "auth_method": DesktopServerAuthMethod;
    "password"?: string;
    "private_key"?: string;
    "group"?: string;
    "tags"?: string[];
    "status": DesktopServerStatus;
    "last_connected"?: string;
    "description"?: string;
    "created_at": string;
    "updated_at": string;

    /** Creates a new DesktopServer instance. */
    constructor($$source: Partial<DesktopServer> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("user_id" in $$source)) {
            this["user_id"] = "";
        }
        if (!("host" in $$source)) {
            this["host"] = "";
        }
        if (!("port" in $$source)) {
            this["port"] = 0;
        }
        if (!("username" in $$source)) {
            this["username"] = "";
        }
        if (!("auth_method" in $$source)) {
            this["auth_method"] = DesktopServerAuthMethod.$zero;
        }
        if (!("status" in $$source)) {
            this["status"] = DesktopServerStatus.$zero;
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = "";
        }
        if (!("updated_at" in $$source)) {
            this["updated_at"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DesktopServer instance from a string or object.
     */
    static createFrom($$source: any = {}): DesktopServer {
        const $$createField10_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField10_0($$parsedSource["tags"]);
        }
        return new DesktopServer($$parsedSource as Partial<DesktopServer>);
    }
}

export enum DesktopServerAuthMethod {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    DesktopServerAuthPassword = "password",
    DesktopServerAuthKey = "key",
};

export class DesktopServerCommandInput {
    "serverId": string;
    "command": string;
    "timeoutMs"?: number;

    /** Creates a new DesktopServerCommandInput instance. */
    constructor($$source: Partial<DesktopServerCommandInput> = {}) {
        if (!("serverId" in $$source)) {
            this["serverId"] = "";
        }
        if (!("command" in $$source)) {
            this["command"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DesktopServerCommandInput instance from a string or object.
     */
    static createFrom($$source: any = {}): DesktopServerCommandInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DesktopServerCommandInput($$parsedSource as Partial<DesktopServerCommandInput>);
    }
}

export class DesktopServerCommandResult {
    "serverId": string;
    "command": string;
    "output": string;
    "exitCode": number;
    "durationMs": number;
    "startedAt": string;
    "completedAt": string;

    /** Creates a new DesktopServerCommandResult instance. */
    constructor($$source: Partial<DesktopServerCommandResult> = {}) {
        if (!("serverId" in $$source)) {
            this["serverId"] = "";
        }
        if (!("command" in $$source)) {
            this["command"] = "";
        }
        if (!("output" in $$source)) {
            this["output"] = "";
        }
        if (!("exitCode" in $$source)) {
            this["exitCode"] = 0;
        }
        if (!("durationMs" in $$source)) {
            this["durationMs"] = 0;
        }
        if (!("startedAt" in $$source)) {
            this["startedAt"] = "";
        }
        if (!("completedAt" in $$source)) {
            this["completedAt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DesktopServerCommandResult instance from a string or object.
     */
    static createFrom($$source: any = {}): DesktopServerCommandResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DesktopServerCommandResult($$parsedSource as Partial<DesktopServerCommandResult>);
    }
}

export class DesktopServerInput {
    "name"?: string;
    "host": string;
    "port": number;
    "username": string;
    "auth_method": DesktopServerAuthMethod;
    "password"?: string;
    "private_key"?: string;
    "group"?: string;
    "tags"?: string[];
    "description"?: string;

    /** Creates a new DesktopServerInput instance. */
    constructor($$source: Partial<DesktopServerInput> = {}) {
        if (!("host" in $$source)) {
            this["host"] = "";
        }
        if (!("port" in $$source)) {
            this["port"] = 0;
        }
        if (!("username" in $$source)) {
            this["username"] = "";
        }
        if (!("auth_method" in $$source)) {
            this["auth_method"] = DesktopServerAuthMethod.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DesktopServerInput instance from a string or object.
     */
    static createFrom($$source: any = {}): DesktopServerInput {
        const $$createField8_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField8_0($$parsedSource["tags"]);
        }
        return new DesktopServerInput($$parsedSource as Partial<DesktopServerInput>);
    }
}

export class DesktopServerListParams {
    "page"?: number;
    "limit"?: number;
    "search"?: string;
    "group"?: string;

    /** Creates a new DesktopServerListParams instance. */
    constructor($$source: Partial<DesktopServerListParams> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DesktopServerListParams instance from a string or object.
     */
    static createFrom($$source: any = {}): DesktopServerListParams {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DesktopServerListParams($$parsedSource as Partial<DesktopServerListParams>);
    }
}

export class DesktopServerListResult {
    "data": DesktopServer[];
    "total": number;
    "page": number;
    "limit": number;

    /** Creates a new DesktopServerListResult instance. */
    constructor($$source: Partial<DesktopServerListResult> = {}) {
        if (!("data" in $$source)) {
            this["data"] = [];
        }
        if (!("total" in $$source)) {
            this["total"] = 0;
        }
        if (!("page" in $$source)) {
            this["page"] = 0;
        }
        if (!("limit" in $$source)) {
            this["limit"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DesktopServerListResult instance from a string or object.
     */
    static createFrom($$source: any = {}): DesktopServerListResult {
        const $$createField0_0 = $$createType19;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("data" in $$parsedSource) {
            $$parsedSource["data"] = $$createField0_0($$parsedSource["data"]);
        }
        return new DesktopServerListResult($$parsedSource as Partial<DesktopServerListResult>);
    }
}

export enum DesktopServerStatus {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    DesktopServerOnline = "online",
    DesktopServerOffline = "offline",
};

export class DesktopTerminalCloseInput {
    "clientId": string;

    /** Creates a new DesktopTerminalCloseInput instance. */
    constructor($$source: Partial<DesktopTerminalCloseInput> = {}) {
        if (!("clientId" in $$source)) {
            this["clientId"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DesktopTerminalCloseInput instance from a string or object.
     */
    static createFrom($$source: any = {}): DesktopTerminalCloseInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DesktopTerminalCloseInput($$parsedSource as Partial<DesktopTerminalCloseInput>);
    }
}

export class DesktopTerminalResizeInput {
    "clientId": string;
    "cols": number;
    "rows": number;

    /** Creates a new DesktopTerminalResizeInput instance. */
    constructor($$source: Partial<DesktopTerminalResizeInput> = {}) {
        if (!("clientId" in $$source)) {
            this["clientId"] = "";
        }
        if (!("cols" in $$source)) {
            this["cols"] = 0;
        }
        if (!("rows" in $$source)) {
            this["rows"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DesktopTerminalResizeInput instance from a string or object.
     */
    static createFrom($$source: any = {}): DesktopTerminalResizeInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DesktopTerminalResizeInput($$parsedSource as Partial<DesktopTerminalResizeInput>);
    }
}

export class DesktopTerminalStartInput {
    "clientId": string;
    "serverId": string;
    "cols": number;
    "rows": number;

    /** Creates a new DesktopTerminalStartInput instance. */
    constructor($$source: Partial<DesktopTerminalStartInput> = {}) {
        if (!("clientId" in $$source)) {
            this["clientId"] = "";
        }
        if (!("serverId" in $$source)) {
            this["serverId"] = "";
        }
        if (!("cols" in $$source)) {
            this["cols"] = 0;
        }
        if (!("rows" in $$source)) {
            this["rows"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DesktopTerminalStartInput instance from a string or object.
     */
    static createFrom($$source: any = {}): DesktopTerminalStartInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DesktopTerminalStartInput($$parsedSource as Partial<DesktopTerminalStartInput>);
    }
}

export class DesktopTerminalWriteInput {
    "clientId": string;
    "data": string;

    /** Creates a new DesktopTerminalWriteInput instance. */
    constructor($$source: Partial<DesktopTerminalWriteInput> = {}) {
        if (!("clientId" in $$source)) {
            this["clientId"] = "";
        }
        if (!("data" in $$source)) {
            this["data"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DesktopTerminalWriteInput instance from a string or object.
     */
    static createFrom($$source: any = {}): DesktopTerminalWriteInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DesktopTerminalWriteInput($$parsedSource as Partial<DesktopTerminalWriteInput>);
    }
}

export class DesktopUserAIConfig {
    "use_system_config": boolean;
    "custom_enabled": boolean;
    "custom_provider": string;
    "custom_endpoint": string;
    "custom_models": string;
    "has_api_key": boolean;

    /** Creates a new DesktopUserAIConfig instance. */
    constructor($$source: Partial<DesktopUserAIConfig> = {}) {
        if (!("use_system_config" in $$source)) {
            this["use_system_config"] = false;
        }
        if (!("custom_enabled" in $$source)) {
            this["custom_enabled"] = false;
        }
        if (!("custom_provider" in $$source)) {
            this["custom_provider"] = "";
        }
        if (!("custom_endpoint" in $$source)) {
            this["custom_endpoint"] = "";
        }
        if (!("custom_models" in $$source)) {
            this["custom_models"] = "";
        }
        if (!("has_api_key" in $$source)) {
            this["has_api_key"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DesktopUserAIConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): DesktopUserAIConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DesktopUserAIConfig($$parsedSource as Partial<DesktopUserAIConfig>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = DesktopAISessionScope.createFrom;
const $$createType2 = $Create.Nullable($$createType1);
const $$createType3 = DesktopAISessionView.createFrom;
const $$createType4 = DesktopAISessionListItem.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = DesktopAIMessageView.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = DesktopAITaskView.createFrom;
const $$createType9 = $Create.Array($$createType8);
const $$createType10 = $Create.Map($Create.Any, $Create.Any);
const $$createType11 = $Create.Array($$createType10);
const $$createType12 = DesktopAIToolView.createFrom;
const $$createType13 = $Create.Array($$createType12);
const $$createType14 = DesktopActivityLogItem.createFrom;
const $$createType15 = $Create.Array($$createType14);
const $$createType16 = $Create.Map($Create.Any, $Create.Any);
const $$createType17 = $Create.Map($Create.Any, $Create.Any);
const $$createType18 = DesktopServer.createFrom;
const $$createType19 = $Create.Array($$createType18);
