// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class DesktopAIConfigStatus {
    "configured": boolean;
    "provider"?: string;
    "model"?: string;
    "models"?: string[];
    "has_key": boolean;
    "message"?: string;

    /** Creates a new DesktopAIConfigStatus instance. */
    constructor($$source: Partial<DesktopAIConfigStatus> = {}) {
        if (!("configured" in $$source)) {
            this["configured"] = false;
        }
        if (!("has_key" in $$source)) {
            this["has_key"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DesktopAIConfigStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): DesktopAIConfigStatus {
        const $$createField3_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("models" in $$parsedSource) {
            $$parsedSource["models"] = $$createField3_0($$parsedSource["models"]);
        }
        return new DesktopAIConfigStatus($$parsedSource as Partial<DesktopAIConfigStatus>);
    }
}

export class DesktopAICreateSessionInput {
    "model"?: string;
    "permission_mode"?: DesktopAIPermissionMode;
    "scope"?: DesktopAISessionScope | null;

    /** Creates a new DesktopAICreateSessionInput instance. */
    constructor($$source: Partial<DesktopAICreateSessionInput> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DesktopAICreateSessionInput instance from a string or object.
     */
    static createFrom($$source: any = {}): DesktopAICreateSessionInput {
        const $$createField2_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("scope" in $$parsedSource) {
            $$parsedSource["scope"] = $$createField2_0($$parsedSource["scope"]);
        }
        return new DesktopAICreateSessionInput($$parsedSource as Partial<DesktopAICreateSessionInput>);
    }
}

export class DesktopAICreateSessionResponse {
    "session_id": string;
    "session": DesktopAISessionView;
    "default_transport": string;

    /** Creates a new DesktopAICreateSessionResponse instance. */
    constructor($$source: Partial<DesktopAICreateSessionResponse> = {}) {
        if (!("session_id" in $$source)) {
            this["session_id"] = "";
        }
        if (!("session" in $$source)) {
            this["session"] = (new DesktopAISessionView());
        }
        if (!("default_transport" in $$source)) {
            this["default_transport"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DesktopAICreateSessionResponse instance from a string or object.
     */
    static createFrom($$source: any = {}): DesktopAICreateSessionResponse {
        const $$createField1_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("session" in $$parsedSource) {
            $$parsedSource["session"] = $$createField1_0($$parsedSource["session"]);
        }
        return new DesktopAICreateSessionResponse($$parsedSource as Partial<DesktopAICreateSessionResponse>);
    }
}

export class DesktopAIListSessionsParams {
    "page"?: number;
    "limit"?: number;
    "q"?: string;
    "scope_kind"?: string;
    "terminal_session_id"?: string;
    "server_id"?: string;

    /** Creates a new DesktopAIListSessionsParams instance. */
    constructor($$source: Partial<DesktopAIListSessionsParams> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DesktopAIListSessionsParams instance from a string or object.
     */
    static createFrom($$source: any = {}): DesktopAIListSessionsParams {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DesktopAIListSessionsParams($$parsedSource as Partial<DesktopAIListSessionsParams>);
    }
}

export class DesktopAIListSessionsResult {
    "items": DesktopAISessionListItem[];
    "total": number;

    /** Creates a new DesktopAIListSessionsResult instance. */
    constructor($$source: Partial<DesktopAIListSessionsResult> = {}) {
        if (!("items" in $$source)) {
            this["items"] = [];
        }
        if (!("total" in $$source)) {
            this["total"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DesktopAIListSessionsResult instance from a string or object.
     */
    static createFrom($$source: any = {}): DesktopAIListSessionsResult {
        const $$createField0_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("items" in $$parsedSource) {
            $$parsedSource["items"] = $$createField0_0($$parsedSource["items"]);
        }
        return new DesktopAIListSessionsResult($$parsedSource as Partial<DesktopAIListSessionsResult>);
    }
}

export class DesktopAIMessageView {
    "id": string;
    "role": string;
    "content": string;
    "created_at": string;

    /** Creates a new DesktopAIMessageView instance. */
    constructor($$source: Partial<DesktopAIMessageView> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("role" in $$source)) {
            this["role"] = "";
        }
        if (!("content" in $$source)) {
            this["content"] = "";
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DesktopAIMessageView instance from a string or object.
     */
    static createFrom($$source: any = {}): DesktopAIMessageView {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DesktopAIMessageView($$parsedSource as Partial<DesktopAIMessageView>);
    }
}

export enum DesktopAIPermissionMode {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    DesktopAIPermissionReadonly = "readonly",
    DesktopAIPermissionBalanced = "balanced",
    DesktopAIPermissionPrivileged = "privileged",
};

export class DesktopAISendMessageInput {
    "session_id": string;
    "content": string;
    "context"?: string;
    "model"?: string;
    "permission_mode"?: DesktopAIPermissionMode;
    "scope"?: DesktopAISessionScope | null;

    /** Creates a new DesktopAISendMessageInput instance. */
    constructor($$source: Partial<DesktopAISendMessageInput> = {}) {
        if (!("session_id" in $$source)) {
            this["session_id"] = "";
        }
        if (!("content" in $$source)) {
            this["content"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DesktopAISendMessageInput instance from a string or object.
     */
    static createFrom($$source: any = {}): DesktopAISendMessageInput {
        const $$createField5_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("scope" in $$parsedSource) {
            $$parsedSource["scope"] = $$createField5_0($$parsedSource["scope"]);
        }
        return new DesktopAISendMessageInput($$parsedSource as Partial<DesktopAISendMessageInput>);
    }
}

export class DesktopAISessionListItem {
    "id": string;
    "model": string;
    "permission_mode": DesktopAIPermissionMode;
    "status": DesktopAISessionStatus;
    "title": string;
    "custom_title": boolean;
    "message_count": number;
    "task_count": number;
    "created_at": string;
    "updated_at": string;

    /** Creates a new DesktopAISessionListItem instance. */
    constructor($$source: Partial<DesktopAISessionListItem> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("model" in $$source)) {
            this["model"] = "";
        }
        if (!("permission_mode" in $$source)) {
            this["permission_mode"] = DesktopAIPermissionMode.$zero;
        }
        if (!("status" in $$source)) {
            this["status"] = DesktopAISessionStatus.$zero;
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("custom_title" in $$source)) {
            this["custom_title"] = false;
        }
        if (!("message_count" in $$source)) {
            this["message_count"] = 0;
        }
        if (!("task_count" in $$source)) {
            this["task_count"] = 0;
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = "";
        }
        if (!("updated_at" in $$source)) {
            this["updated_at"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DesktopAISessionListItem instance from a string or object.
     */
    static createFrom($$source: any = {}): DesktopAISessionListItem {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DesktopAISessionListItem($$parsedSource as Partial<DesktopAISessionListItem>);
    }
}

export class DesktopAISessionScope {
    "kind"?: string;
    "terminal_session_id"?: string;
    "server_id"?: string;
    "server_name"?: string;
    "host"?: string;
    "port"?: number;
    "username"?: string;

    /** Creates a new DesktopAISessionScope instance. */
    constructor($$source: Partial<DesktopAISessionScope> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DesktopAISessionScope instance from a string or object.
     */
    static createFrom($$source: any = {}): DesktopAISessionScope {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DesktopAISessionScope($$parsedSource as Partial<DesktopAISessionScope>);
    }
}

export enum DesktopAISessionStatus {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    DesktopAISessionIdle = "idle",
    DesktopAISessionRunning = "running",
    DesktopAISessionClosed = "closed",
};

export class DesktopAISessionView {
    "id": string;
    "model": string;
    "permission_mode": DesktopAIPermissionMode;
    "scope"?: DesktopAISessionScope | null;
    "status": DesktopAISessionStatus;
    "created_at": string;
    "updated_at": string;
    "messages": DesktopAIMessageView[];
    "tasks": DesktopAITaskView[];
    "ui_messages": { [_ in string]?: any }[];
    "available_tools": DesktopAIToolView[];
    "default_transport": string;

    /** Creates a new DesktopAISessionView instance. */
    constructor($$source: Partial<DesktopAISessionView> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("model" in $$source)) {
            this["model"] = "";
        }
        if (!("permission_mode" in $$source)) {
            this["permission_mode"] = DesktopAIPermissionMode.$zero;
        }
        if (!("status" in $$source)) {
            this["status"] = DesktopAISessionStatus.$zero;
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = "";
        }
        if (!("updated_at" in $$source)) {
            this["updated_at"] = "";
        }
        if (!("messages" in $$source)) {
            this["messages"] = [];
        }
        if (!("tasks" in $$source)) {
            this["tasks"] = [];
        }
        if (!("ui_messages" in $$source)) {
            this["ui_messages"] = [];
        }
        if (!("available_tools" in $$source)) {
            this["available_tools"] = [];
        }
        if (!("default_transport" in $$source)) {
            this["default_transport"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DesktopAISessionView instance from a string or object.
     */
    static createFrom($$source: any = {}): DesktopAISessionView {
        const $$createField3_0 = $$createType2;
        const $$createField7_0 = $$createType7;
        const $$createField8_0 = $$createType9;
        const $$createField9_0 = $$createType11;
        const $$createField10_0 = $$createType13;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("scope" in $$parsedSource) {
            $$parsedSource["scope"] = $$createField3_0($$parsedSource["scope"]);
        }
        if ("messages" in $$parsedSource) {
            $$parsedSource["messages"] = $$createField7_0($$parsedSource["messages"]);
        }
        if ("tasks" in $$parsedSource) {
            $$parsedSource["tasks"] = $$createField8_0($$parsedSource["tasks"]);
        }
        if ("ui_messages" in $$parsedSource) {
            $$parsedSource["ui_messages"] = $$createField9_0($$parsedSource["ui_messages"]);
        }
        if ("available_tools" in $$parsedSource) {
            $$parsedSource["available_tools"] = $$createField10_0($$parsedSource["available_tools"]);
        }
        return new DesktopAISessionView($$parsedSource as Partial<DesktopAISessionView>);
    }
}

export type DesktopAITaskStatus = string;

export class DesktopAITaskView {
    "id": string;
    "tool_call_id": string;
    "tool_name": string;
    "tool_display_name"?: string;
    "summary"?: string;
    "status": DesktopAITaskStatus;
    "dangerous": boolean;
    "requires_confirmation": boolean;
    "arguments"?: { [_ in string]?: any };
    "result"?: string;
    "error"?: string;
    "created_at": string;
    "updated_at": string;
    "custom_title"?: boolean;

    /** Creates a new DesktopAITaskView instance. */
    constructor($$source: Partial<DesktopAITaskView> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("tool_call_id" in $$source)) {
            this["tool_call_id"] = "";
        }
        if (!("tool_name" in $$source)) {
            this["tool_name"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("dangerous" in $$source)) {
            this["dangerous"] = false;
        }
        if (!("requires_confirmation" in $$source)) {
            this["requires_confirmation"] = false;
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = "";
        }
        if (!("updated_at" in $$source)) {
            this["updated_at"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DesktopAITaskView instance from a string or object.
     */
    static createFrom($$source: any = {}): DesktopAITaskView {
        const $$createField8_0 = $$createType10;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("arguments" in $$parsedSource) {
            $$parsedSource["arguments"] = $$createField8_0($$parsedSource["arguments"]);
        }
        return new DesktopAITaskView($$parsedSource as Partial<DesktopAITaskView>);
    }
}

export class DesktopAIToolView {
    "name": string;
    "display_name"?: string;
    "description": string;
    "dangerous": boolean;

    /** Creates a new DesktopAIToolView instance. */
    constructor($$source: Partial<DesktopAIToolView> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("dangerous" in $$source)) {
            this["dangerous"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DesktopAIToolView instance from a string or object.
     */
    static createFrom($$source: any = {}): DesktopAIToolView {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DesktopAIToolView($$parsedSource as Partial<DesktopAIToolView>);
    }
}

export class DesktopActivityLogItem {
    "id": string;
    "action": string;
    "resource": string;
    "status": DesktopActivityLogStatus;
    "serverId"?: string;
    "durationMs"?: number;
    "detail"?: string;
    "createdAt": string;

    /** Creates a new DesktopActivityLogItem instance. */
    constructor($$source: Partial<DesktopActivityLogItem> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("action" in $$source)) {
            this["action"] = "";
        }
        if (!("resource" in $$source)) {
            this["resource"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = DesktopActivityLogStatus.$zero;
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DesktopActivityLogItem instance from a string or object.
     */
    static createFrom($$source: any = {}): DesktopActivityLogItem {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DesktopActivityLogItem($$parsedSource as Partial<DesktopActivityLogItem>);
    }
}

export class DesktopActivityLogListParams {
    "page"?: number;
    "limit"?: number;
    "action"?: string;
    "serverId"?: string;
    "status"?: DesktopActivityLogStatus;
    "startDate"?: string;
    "endDate"?: string;

    /** Creates a new DesktopActivityLogListParams instance. */
    constructor($$source: Partial<DesktopActivityLogListParams> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DesktopActivityLogListParams instance from a string or object.
     */
    static createFrom($$source: any = {}): DesktopActivityLogListParams {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DesktopActivityLogListParams($$parsedSource as Partial<DesktopActivityLogListParams>);
    }
}

export class DesktopActivityLogListResult {
    "items": DesktopActivityLogItem[];
    "total": number;
    "page": number;
    "pageSize": number;
    "totalPages": number;

    /** Creates a new DesktopActivityLogListResult instance. */
    constructor($$source: Partial<DesktopActivityLogListResult> = {}) {
        if (!("items" in $$source)) {
            this["items"] = [];
        }
        if (!("total" in $$source)) {
            this["total"] = 0;
        }
        if (!("page" in $$source)) {
            this["page"] = 0;
        }
        if (!("pageSize" in $$source)) {
            this["pageSize"] = 0;
        }
        if (!("totalPages" in $$source)) {
            this["totalPages"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DesktopActivityLogListResult instance from a string or object.
     */
    static createFrom($$source: any = {}): DesktopActivityLogListResult {
        const $$createField0_0 = $$createType15;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("items" in $$parsedSource) {
            $$parsedSource["items"] = $$createField0_0($$parsedSource["items"]);
        }
        return new DesktopActivityLogListResult($$parsedSource as Partial<DesktopActivityLogListResult>);
    }
}

export class DesktopActivityLogRecordInput {
    "action": string;
    "resource": string;
    "status": DesktopActivityLogStatus;
    "serverId"?: string;
    "durationMs"?: number;
    "detail"?: string;

    /** Creates a new DesktopActivityLogRecordInput instance. */
    constructor($$source: Partial<DesktopActivityLogRecordInput> = {}) {
        if (!("action" in $$source)) {
            this["action"] = "";
        }
        if (!("resource" in $$source)) {
            this["resource"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = DesktopActivityLogStatus.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DesktopActivityLogRecordInput instance from a string or object.
     */
    static createFrom($$source: any = {}): DesktopActivityLogRecordInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DesktopActivityLogRecordInput($$parsedSource as Partial<DesktopActivityLogRecordInput>);
    }
}

export class DesktopActivityLogStatistics {
    "total": number;
    "successCount": number;
    "failureCount": number;
    "byAction": { [_ in string]?: number };

    /** Creates a new DesktopActivityLogStatistics instance. */
    constructor($$source: Partial<DesktopActivityLogStatistics> = {}) {
        if (!("total" in $$source)) {
            this["total"] = 0;
        }
        if (!("successCount" in $$source)) {
            this["successCount"] = 0;
        }
        if (!("failureCount" in $$source)) {
            this["failureCount"] = 0;
        }
        if (!("byAction" in $$source)) {
            this["byAction"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DesktopActivityLogStatistics instance from a string or object.
     */
    static createFrom($$source: any = {}): DesktopActivityLogStatistics {
        const $$createField3_0 = $$createType16;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("byAction" in $$parsedSource) {
            $$parsedSource["byAction"] = $$createField3_0($$parsedSource["byAction"]);
        }
        return new DesktopActivityLogStatistics($$parsedSource as Partial<DesktopActivityLogStatistics>);
    }
}

export enum DesktopActivityLogStatus {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    DesktopActivityLogSuccess = "success",
    DesktopActivityLogFailure = "failure",
    DesktopActivityLogWarning = "warning",
};

export type DesktopCapability = string;

export class DesktopDockerContainer {
    "id": string;
    "names": string[];
    "image": string;
    "imageId": string;
    "command": string;
    "created": number;
    "status": string;
    "state": string;
    "ports": DesktopDockerPort[];
    "labels": { [_ in string]?: string };
    "mounts": DesktopDockerMount[];

    /** Creates a new DesktopDockerContainer instance. */
    constructor($$source: Partial<DesktopDockerContainer> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("names" in $$source)) {
            this["names"] = [];
        }
        if (!("image" in $$source)) {
            this["image"] = "";
        }
        if (!("imageId" in $$source)) {
            this["imageId"] = "";
        }
        if (!("command" in $$source)) {
            this["command"] = "";
        }
        if (!("created" in $$source)) {
            this["created"] = 0;
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("state" in $$source)) {
            this["state"] = "";
        }
        if (!("ports" in $$source)) {
            this["ports"] = [];
        }
        if (!("labels" in $$source)) {
            this["labels"] = {};
        }
        if (!("mounts" in $$source)) {
            this["mounts"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DesktopDockerContainer instance from a string or object.
     */
    static createFrom($$source: any = {}): DesktopDockerContainer {
        const $$createField1_0 = $$createType0;
        const $$createField8_0 = $$createType18;
        const $$createField9_0 = $$createType19;
        const $$createField10_0 = $$createType21;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("names" in $$parsedSource) {
            $$parsedSource["names"] = $$createField1_0($$parsedSource["names"]);
        }
        if ("ports" in $$parsedSource) {
            $$parsedSource["ports"] = $$createField8_0($$parsedSource["ports"]);
        }
        if ("labels" in $$parsedSource) {
            $$parsedSource["labels"] = $$createField9_0($$parsedSource["labels"]);
        }
        if ("mounts" in $$parsedSource) {
            $$parsedSource["mounts"] = $$createField10_0($$parsedSource["mounts"]);
        }
        return new DesktopDockerContainer($$parsedSource as Partial<DesktopDockerContainer>);
    }
}

export class DesktopDockerContainerInput {
    "serverId": string;
    "containerId": string;

    /** Creates a new DesktopDockerContainerInput instance. */
    constructor($$source: Partial<DesktopDockerContainerInput> = {}) {
        if (!("serverId" in $$source)) {
            this["serverId"] = "";
        }
        if (!("containerId" in $$source)) {
            this["containerId"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DesktopDockerContainerInput instance from a string or object.
     */
    static createFrom($$source: any = {}): DesktopDockerContainerInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DesktopDockerContainerInput($$parsedSource as Partial<DesktopDockerContainerInput>);
    }
}

export class DesktopDockerContainerLogsInput {
    "serverId": string;
    "containerId": string;
    "tail"?: number;
    "encoding"?: string;

    /** Creates a new DesktopDockerContainerLogsInput instance. */
    constructor($$source: Partial<DesktopDockerContainerLogsInput> = {}) {
        if (!("serverId" in $$source)) {
            this["serverId"] = "";
        }
        if (!("containerId" in $$source)) {
            this["containerId"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DesktopDockerContainerLogsInput instance from a string or object.
     */
    static createFrom($$source: any = {}): DesktopDockerContainerLogsInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DesktopDockerContainerLogsInput($$parsedSource as Partial<DesktopDockerContainerLogsInput>);
    }
}

export class DesktopDockerContainerLogsResult {
    "data": string;
    "container_id": string;
    "lines": number;
    "encoding": string;

    /** Creates a new DesktopDockerContainerLogsResult instance. */
    constructor($$source: Partial<DesktopDockerContainerLogsResult> = {}) {
        if (!("data" in $$source)) {
            this["data"] = "";
        }
        if (!("container_id" in $$source)) {
            this["container_id"] = "";
        }
        if (!("lines" in $$source)) {
            this["lines"] = 0;
        }
        if (!("encoding" in $$source)) {
            this["encoding"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DesktopDockerContainerLogsResult instance from a string or object.
     */
    static createFrom($$source: any = {}): DesktopDockerContainerLogsResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DesktopDockerContainerLogsResult($$parsedSource as Partial<DesktopDockerContainerLogsResult>);
    }
}

export class DesktopDockerContainerStats {
    "containerId": string;
    "name": string;
    "cpuPercent": number;
    "memoryUsage": number;
    "memoryLimit": number;
    "memoryPercent": number;
    "networkIn": number;
    "networkOut": number;
    "blockRead": number;
    "blockWrite": number;
    "pids": number;

    /** Creates a new DesktopDockerContainerStats instance. */
    constructor($$source: Partial<DesktopDockerContainerStats> = {}) {
        if (!("containerId" in $$source)) {
            this["containerId"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("cpuPercent" in $$source)) {
            this["cpuPercent"] = 0;
        }
        if (!("memoryUsage" in $$source)) {
            this["memoryUsage"] = 0;
        }
        if (!("memoryLimit" in $$source)) {
            this["memoryLimit"] = 0;
        }
        if (!("memoryPercent" in $$source)) {
            this["memoryPercent"] = 0;
        }
        if (!("networkIn" in $$source)) {
            this["networkIn"] = 0;
        }
        if (!("networkOut" in $$source)) {
            this["networkOut"] = 0;
        }
        if (!("blockRead" in $$source)) {
            this["blockRead"] = 0;
        }
        if (!("blockWrite" in $$source)) {
            this["blockWrite"] = 0;
        }
        if (!("pids" in $$source)) {
            this["pids"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DesktopDockerContainerStats instance from a string or object.
     */
    static createFrom($$source: any = {}): DesktopDockerContainerStats {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DesktopDockerContainerStats($$parsedSource as Partial<DesktopDockerContainerStats>);
    }
}

export class DesktopDockerContainersResult {
    "data": DesktopDockerContainer[];
    "total": number;

    /** Creates a new DesktopDockerContainersResult instance. */
    constructor($$source: Partial<DesktopDockerContainersResult> = {}) {
        if (!("data" in $$source)) {
            this["data"] = [];
        }
        if (!("total" in $$source)) {
            this["total"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DesktopDockerContainersResult instance from a string or object.
     */
    static createFrom($$source: any = {}): DesktopDockerContainersResult {
        const $$createField0_0 = $$createType23;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("data" in $$parsedSource) {
            $$parsedSource["data"] = $$createField0_0($$parsedSource["data"]);
        }
        return new DesktopDockerContainersResult($$parsedSource as Partial<DesktopDockerContainersResult>);
    }
}

export class DesktopDockerImage {
    "id": string;
    "repository": string;
    "tag": string;
    "created": number;
    "size": number;
    "virtualSize": number;

    /** Creates a new DesktopDockerImage instance. */
    constructor($$source: Partial<DesktopDockerImage> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("repository" in $$source)) {
            this["repository"] = "";
        }
        if (!("tag" in $$source)) {
            this["tag"] = "";
        }
        if (!("created" in $$source)) {
            this["created"] = 0;
        }
        if (!("size" in $$source)) {
            this["size"] = 0;
        }
        if (!("virtualSize" in $$source)) {
            this["virtualSize"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DesktopDockerImage instance from a string or object.
     */
    static createFrom($$source: any = {}): DesktopDockerImage {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DesktopDockerImage($$parsedSource as Partial<DesktopDockerImage>);
    }
}

export class DesktopDockerImageUpdateCheckResult {
    "hasUpdate": boolean;
    "imageName": string;
    "containerName": string;
    "updateCommand": string;
    "error"?: string;

    /** Creates a new DesktopDockerImageUpdateCheckResult instance. */
    constructor($$source: Partial<DesktopDockerImageUpdateCheckResult> = {}) {
        if (!("hasUpdate" in $$source)) {
            this["hasUpdate"] = false;
        }
        if (!("imageName" in $$source)) {
            this["imageName"] = "";
        }
        if (!("containerName" in $$source)) {
            this["containerName"] = "";
        }
        if (!("updateCommand" in $$source)) {
            this["updateCommand"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DesktopDockerImageUpdateCheckResult instance from a string or object.
     */
    static createFrom($$source: any = {}): DesktopDockerImageUpdateCheckResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DesktopDockerImageUpdateCheckResult($$parsedSource as Partial<DesktopDockerImageUpdateCheckResult>);
    }
}

export class DesktopDockerImagesResult {
    "data": DesktopDockerImage[];
    "total": number;

    /** Creates a new DesktopDockerImagesResult instance. */
    constructor($$source: Partial<DesktopDockerImagesResult> = {}) {
        if (!("data" in $$source)) {
            this["data"] = [];
        }
        if (!("total" in $$source)) {
            this["total"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DesktopDockerImagesResult instance from a string or object.
     */
    static createFrom($$source: any = {}): DesktopDockerImagesResult {
        const $$createField0_0 = $$createType25;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("data" in $$parsedSource) {
            $$parsedSource["data"] = $$createField0_0($$parsedSource["data"]);
        }
        return new DesktopDockerImagesResult($$parsedSource as Partial<DesktopDockerImagesResult>);
    }
}

export class DesktopDockerListContainersInput {
    "serverId": string;
    "all"?: boolean;

    /** Creates a new DesktopDockerListContainersInput instance. */
    constructor($$source: Partial<DesktopDockerListContainersInput> = {}) {
        if (!("serverId" in $$source)) {
            this["serverId"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DesktopDockerListContainersInput instance from a string or object.
     */
    static createFrom($$source: any = {}): DesktopDockerListContainersInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DesktopDockerListContainersInput($$parsedSource as Partial<DesktopDockerListContainersInput>);
    }
}

export class DesktopDockerMount {
    "type": string;
    "source": string;
    "destination": string;
    "mode": string;
    "rw": boolean;

    /** Creates a new DesktopDockerMount instance. */
    constructor($$source: Partial<DesktopDockerMount> = {}) {
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("source" in $$source)) {
            this["source"] = "";
        }
        if (!("destination" in $$source)) {
            this["destination"] = "";
        }
        if (!("mode" in $$source)) {
            this["mode"] = "";
        }
        if (!("rw" in $$source)) {
            this["rw"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DesktopDockerMount instance from a string or object.
     */
    static createFrom($$source: any = {}): DesktopDockerMount {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DesktopDockerMount($$parsedSource as Partial<DesktopDockerMount>);
    }
}

export class DesktopDockerPort {
    "ip"?: string;
    "privatePort": number;
    "publicPort"?: number;
    "type": string;

    /** Creates a new DesktopDockerPort instance. */
    constructor($$source: Partial<DesktopDockerPort> = {}) {
        if (!("privatePort" in $$source)) {
            this["privatePort"] = 0;
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DesktopDockerPort instance from a string or object.
     */
    static createFrom($$source: any = {}): DesktopDockerPort {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DesktopDockerPort($$parsedSource as Partial<DesktopDockerPort>);
    }
}

export class DesktopDockerRemoveContainerInput {
    "serverId": string;
    "containerId": string;
    "force"?: boolean;

    /** Creates a new DesktopDockerRemoveContainerInput instance. */
    constructor($$source: Partial<DesktopDockerRemoveContainerInput> = {}) {
        if (!("serverId" in $$source)) {
            this["serverId"] = "";
        }
        if (!("containerId" in $$source)) {
            this["containerId"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DesktopDockerRemoveContainerInput instance from a string or object.
     */
    static createFrom($$source: any = {}): DesktopDockerRemoveContainerInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DesktopDockerRemoveContainerInput($$parsedSource as Partial<DesktopDockerRemoveContainerInput>);
    }
}

export class DesktopDockerResourcesResult {
    "stats": DesktopDockerContainerStats[];
    "systemInfo": DesktopDockerSystemInfo | null;
    "dockerInstalled": boolean;
    "error"?: string;

    /** Creates a new DesktopDockerResourcesResult instance. */
    constructor($$source: Partial<DesktopDockerResourcesResult> = {}) {
        if (!("stats" in $$source)) {
            this["stats"] = [];
        }
        if (!("systemInfo" in $$source)) {
            this["systemInfo"] = null;
        }
        if (!("dockerInstalled" in $$source)) {
            this["dockerInstalled"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DesktopDockerResourcesResult instance from a string or object.
     */
    static createFrom($$source: any = {}): DesktopDockerResourcesResult {
        const $$createField0_0 = $$createType27;
        const $$createField1_0 = $$createType29;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("stats" in $$parsedSource) {
            $$parsedSource["stats"] = $$createField0_0($$parsedSource["stats"]);
        }
        if ("systemInfo" in $$parsedSource) {
            $$parsedSource["systemInfo"] = $$createField1_0($$parsedSource["systemInfo"]);
        }
        return new DesktopDockerResourcesResult($$parsedSource as Partial<DesktopDockerResourcesResult>);
    }
}

export class DesktopDockerServerInput {
    "serverId": string;

    /** Creates a new DesktopDockerServerInput instance. */
    constructor($$source: Partial<DesktopDockerServerInput> = {}) {
        if (!("serverId" in $$source)) {
            this["serverId"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DesktopDockerServerInput instance from a string or object.
     */
    static createFrom($$source: any = {}): DesktopDockerServerInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DesktopDockerServerInput($$parsedSource as Partial<DesktopDockerServerInput>);
    }
}

export class DesktopDockerSystemInfo {
    "containersRunning": number;
    "containersPaused": number;
    "containersStopped": number;
    "containersTotal": number;
    "imagesCount": number;
    "dockerVersion": string;
    "serverVersion": string;
    "storageDriver": string;
    "totalMemory": number;
    "cpus": number;

    /** Creates a new DesktopDockerSystemInfo instance. */
    constructor($$source: Partial<DesktopDockerSystemInfo> = {}) {
        if (!("containersRunning" in $$source)) {
            this["containersRunning"] = 0;
        }
        if (!("containersPaused" in $$source)) {
            this["containersPaused"] = 0;
        }
        if (!("containersStopped" in $$source)) {
            this["containersStopped"] = 0;
        }
        if (!("containersTotal" in $$source)) {
            this["containersTotal"] = 0;
        }
        if (!("imagesCount" in $$source)) {
            this["imagesCount"] = 0;
        }
        if (!("dockerVersion" in $$source)) {
            this["dockerVersion"] = "";
        }
        if (!("serverVersion" in $$source)) {
            this["serverVersion"] = "";
        }
        if (!("storageDriver" in $$source)) {
            this["storageDriver"] = "";
        }
        if (!("totalMemory" in $$source)) {
            this["totalMemory"] = 0;
        }
        if (!("cpus" in $$source)) {
            this["cpus"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DesktopDockerSystemInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): DesktopDockerSystemInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DesktopDockerSystemInfo($$parsedSource as Partial<DesktopDockerSystemInfo>);
    }
}

export class DesktopMonitorCPUInfo {
    "idleTicks": number;
    "totalTicks": number;
    "coreCount": number;
    "usagePercent": number;

    /** Creates a new DesktopMonitorCPUInfo instance. */
    constructor($$source: Partial<DesktopMonitorCPUInfo> = {}) {
        if (!("idleTicks" in $$source)) {
            this["idleTicks"] = 0;
        }
        if (!("totalTicks" in $$source)) {
            this["totalTicks"] = 0;
        }
        if (!("coreCount" in $$source)) {
            this["coreCount"] = 0;
        }
        if (!("usagePercent" in $$source)) {
            this["usagePercent"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DesktopMonitorCPUInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): DesktopMonitorCPUInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DesktopMonitorCPUInfo($$parsedSource as Partial<DesktopMonitorCPUInfo>);
    }
}

export class DesktopMonitorCollectInput {
    "serverId": string;
    "timeoutMs"?: number;

    /** Creates a new DesktopMonitorCollectInput instance. */
    constructor($$source: Partial<DesktopMonitorCollectInput> = {}) {
        if (!("serverId" in $$source)) {
            this["serverId"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DesktopMonitorCollectInput instance from a string or object.
     */
    static createFrom($$source: any = {}): DesktopMonitorCollectInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DesktopMonitorCollectInput($$parsedSource as Partial<DesktopMonitorCollectInput>);
    }
}

export class DesktopMonitorDiskInfo {
    "mountPoint": string;
    "usedBytes": number;
    "totalBytes": number;

    /** Creates a new DesktopMonitorDiskInfo instance. */
    constructor($$source: Partial<DesktopMonitorDiskInfo> = {}) {
        if (!("mountPoint" in $$source)) {
            this["mountPoint"] = "";
        }
        if (!("usedBytes" in $$source)) {
            this["usedBytes"] = 0;
        }
        if (!("totalBytes" in $$source)) {
            this["totalBytes"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DesktopMonitorDiskInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): DesktopMonitorDiskInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DesktopMonitorDiskInfo($$parsedSource as Partial<DesktopMonitorDiskInfo>);
    }
}

export class DesktopMonitorDockerInfo {
    "containersRunning": number;
    "containersTotal": number;
    "dockerInstalled": boolean;

    /** Creates a new DesktopMonitorDockerInfo instance. */
    constructor($$source: Partial<DesktopMonitorDockerInfo> = {}) {
        if (!("containersRunning" in $$source)) {
            this["containersRunning"] = 0;
        }
        if (!("containersTotal" in $$source)) {
            this["containersTotal"] = 0;
        }
        if (!("dockerInstalled" in $$source)) {
            this["dockerInstalled"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DesktopMonitorDockerInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): DesktopMonitorDockerInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DesktopMonitorDockerInfo($$parsedSource as Partial<DesktopMonitorDockerInfo>);
    }
}

export class DesktopMonitorMemoryInfo {
    "ramUsedBytes": number;
    "ramTotalBytes": number;
    "swapUsedBytes": number;
    "swapTotalBytes": number;

    /** Creates a new DesktopMonitorMemoryInfo instance. */
    constructor($$source: Partial<DesktopMonitorMemoryInfo> = {}) {
        if (!("ramUsedBytes" in $$source)) {
            this["ramUsedBytes"] = 0;
        }
        if (!("ramTotalBytes" in $$source)) {
            this["ramTotalBytes"] = 0;
        }
        if (!("swapUsedBytes" in $$source)) {
            this["swapUsedBytes"] = 0;
        }
        if (!("swapTotalBytes" in $$source)) {
            this["swapTotalBytes"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DesktopMonitorMemoryInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): DesktopMonitorMemoryInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DesktopMonitorMemoryInfo($$parsedSource as Partial<DesktopMonitorMemoryInfo>);
    }
}

export class DesktopMonitorNetworkInfo {
    "bytesRecvTotal": number;
    "bytesSentTotal": number;

    /** Creates a new DesktopMonitorNetworkInfo instance. */
    constructor($$source: Partial<DesktopMonitorNetworkInfo> = {}) {
        if (!("bytesRecvTotal" in $$source)) {
            this["bytesRecvTotal"] = 0;
        }
        if (!("bytesSentTotal" in $$source)) {
            this["bytesSentTotal"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DesktopMonitorNetworkInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): DesktopMonitorNetworkInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DesktopMonitorNetworkInfo($$parsedSource as Partial<DesktopMonitorNetworkInfo>);
    }
}

export class DesktopMonitorSnapshot {
    "systemInfo": DesktopMonitorSystemInfo;
    "cpu": DesktopMonitorCPUInfo;
    "memory": DesktopMonitorMemoryInfo;
    "network": DesktopMonitorNetworkInfo;
    "disks": DesktopMonitorDiskInfo[];
    "docker": DesktopMonitorDockerInfo;
    "sshLatencyMs": number;
    "timestamp": number;
    "collectedAt": string;

    /** Creates a new DesktopMonitorSnapshot instance. */
    constructor($$source: Partial<DesktopMonitorSnapshot> = {}) {
        if (!("systemInfo" in $$source)) {
            this["systemInfo"] = (new DesktopMonitorSystemInfo());
        }
        if (!("cpu" in $$source)) {
            this["cpu"] = (new DesktopMonitorCPUInfo());
        }
        if (!("memory" in $$source)) {
            this["memory"] = (new DesktopMonitorMemoryInfo());
        }
        if (!("network" in $$source)) {
            this["network"] = (new DesktopMonitorNetworkInfo());
        }
        if (!("disks" in $$source)) {
            this["disks"] = [];
        }
        if (!("docker" in $$source)) {
            this["docker"] = (new DesktopMonitorDockerInfo());
        }
        if (!("sshLatencyMs" in $$source)) {
            this["sshLatencyMs"] = 0;
        }
        if (!("timestamp" in $$source)) {
            this["timestamp"] = 0;
        }
        if (!("collectedAt" in $$source)) {
            this["collectedAt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DesktopMonitorSnapshot instance from a string or object.
     */
    static createFrom($$source: any = {}): DesktopMonitorSnapshot {
        const $$createField0_0 = $$createType30;
        const $$createField1_0 = $$createType31;
        const $$createField2_0 = $$createType32;
        const $$createField3_0 = $$createType33;
        const $$createField4_0 = $$createType35;
        const $$createField5_0 = $$createType36;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("systemInfo" in $$parsedSource) {
            $$parsedSource["systemInfo"] = $$createField0_0($$parsedSource["systemInfo"]);
        }
        if ("cpu" in $$parsedSource) {
            $$parsedSource["cpu"] = $$createField1_0($$parsedSource["cpu"]);
        }
        if ("memory" in $$parsedSource) {
            $$parsedSource["memory"] = $$createField2_0($$parsedSource["memory"]);
        }
        if ("network" in $$parsedSource) {
            $$parsedSource["network"] = $$createField3_0($$parsedSource["network"]);
        }
        if ("disks" in $$parsedSource) {
            $$parsedSource["disks"] = $$createField4_0($$parsedSource["disks"]);
        }
        if ("docker" in $$parsedSource) {
            $$parsedSource["docker"] = $$createField5_0($$parsedSource["docker"]);
        }
        return new DesktopMonitorSnapshot($$parsedSource as Partial<DesktopMonitorSnapshot>);
    }
}

export class DesktopMonitorSystemInfo {
    "os": string;
    "hostname": string;
    "cpuModel": string;
    "arch": string;
    "loadAvg": string;
    "uptimeSeconds": number;
    "cpuCores": number;

    /** Creates a new DesktopMonitorSystemInfo instance. */
    constructor($$source: Partial<DesktopMonitorSystemInfo> = {}) {
        if (!("os" in $$source)) {
            this["os"] = "";
        }
        if (!("hostname" in $$source)) {
            this["hostname"] = "";
        }
        if (!("cpuModel" in $$source)) {
            this["cpuModel"] = "";
        }
        if (!("arch" in $$source)) {
            this["arch"] = "";
        }
        if (!("loadAvg" in $$source)) {
            this["loadAvg"] = "";
        }
        if (!("uptimeSeconds" in $$source)) {
            this["uptimeSeconds"] = 0;
        }
        if (!("cpuCores" in $$source)) {
            this["cpuCores"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DesktopMonitorSystemInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): DesktopMonitorSystemInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DesktopMonitorSystemInfo($$parsedSource as Partial<DesktopMonitorSystemInfo>);
    }
}

export type DesktopPreferenceSnapshot = { [_ in string]?: string };

export class DesktopRuntimeInfo {
    "profile": string;
    "version": string;
    "platform": string;
    "arch": string;
    "dataDir": string;
    "capabilities": { [_ in DesktopCapability]?: boolean };

    /** Creates a new DesktopRuntimeInfo instance. */
    constructor($$source: Partial<DesktopRuntimeInfo> = {}) {
        if (!("profile" in $$source)) {
            this["profile"] = "";
        }
        if (!("version" in $$source)) {
            this["version"] = "";
        }
        if (!("platform" in $$source)) {
            this["platform"] = "";
        }
        if (!("arch" in $$source)) {
            this["arch"] = "";
        }
        if (!("dataDir" in $$source)) {
            this["dataDir"] = "";
        }
        if (!("capabilities" in $$source)) {
            this["capabilities"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DesktopRuntimeInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): DesktopRuntimeInfo {
        const $$createField5_0 = $$createType37;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("capabilities" in $$parsedSource) {
            $$parsedSource["capabilities"] = $$createField5_0($$parsedSource["capabilities"]);
        }
        return new DesktopRuntimeInfo($$parsedSource as Partial<DesktopRuntimeInfo>);
    }
}

export class DesktopSFTPBatchDeleteInput {
    "serverId": string;
    "paths": string[];

    /** Creates a new DesktopSFTPBatchDeleteInput instance. */
    constructor($$source: Partial<DesktopSFTPBatchDeleteInput> = {}) {
        if (!("serverId" in $$source)) {
            this["serverId"] = "";
        }
        if (!("paths" in $$source)) {
            this["paths"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DesktopSFTPBatchDeleteInput instance from a string or object.
     */
    static createFrom($$source: any = {}): DesktopSFTPBatchDeleteInput {
        const $$createField1_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("paths" in $$parsedSource) {
            $$parsedSource["paths"] = $$createField1_0($$parsedSource["paths"]);
        }
        return new DesktopSFTPBatchDeleteInput($$parsedSource as Partial<DesktopSFTPBatchDeleteInput>);
    }
}

export class DesktopSFTPBatchDeleteResult {
    "success": string[];
    "failed": DesktopSFTPBatchOperationError[];
    "total": number;

    /** Creates a new DesktopSFTPBatchDeleteResult instance. */
    constructor($$source: Partial<DesktopSFTPBatchDeleteResult> = {}) {
        if (!("success" in $$source)) {
            this["success"] = [];
        }
        if (!("failed" in $$source)) {
            this["failed"] = [];
        }
        if (!("total" in $$source)) {
            this["total"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DesktopSFTPBatchDeleteResult instance from a string or object.
     */
    static createFrom($$source: any = {}): DesktopSFTPBatchDeleteResult {
        const $$createField0_0 = $$createType0;
        const $$createField1_0 = $$createType39;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("success" in $$parsedSource) {
            $$parsedSource["success"] = $$createField0_0($$parsedSource["success"]);
        }
        if ("failed" in $$parsedSource) {
            $$parsedSource["failed"] = $$createField1_0($$parsedSource["failed"]);
        }
        return new DesktopSFTPBatchDeleteResult($$parsedSource as Partial<DesktopSFTPBatchDeleteResult>);
    }
}

export class DesktopSFTPBatchDownloadInput {
    "serverId": string;
    "paths": string[];
    "localPath": string;

    /** Creates a new DesktopSFTPBatchDownloadInput instance. */
    constructor($$source: Partial<DesktopSFTPBatchDownloadInput> = {}) {
        if (!("serverId" in $$source)) {
            this["serverId"] = "";
        }
        if (!("paths" in $$source)) {
            this["paths"] = [];
        }
        if (!("localPath" in $$source)) {
            this["localPath"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DesktopSFTPBatchDownloadInput instance from a string or object.
     */
    static createFrom($$source: any = {}): DesktopSFTPBatchDownloadInput {
        const $$createField1_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("paths" in $$parsedSource) {
            $$parsedSource["paths"] = $$createField1_0($$parsedSource["paths"]);
        }
        return new DesktopSFTPBatchDownloadInput($$parsedSource as Partial<DesktopSFTPBatchDownloadInput>);
    }
}

export class DesktopSFTPBatchOperationError {
    "path": string;
    "error": string;
    "message": string;

    /** Creates a new DesktopSFTPBatchOperationError instance. */
    constructor($$source: Partial<DesktopSFTPBatchOperationError> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("error" in $$source)) {
            this["error"] = "";
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DesktopSFTPBatchOperationError instance from a string or object.
     */
    static createFrom($$source: any = {}): DesktopSFTPBatchOperationError {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DesktopSFTPBatchOperationError($$parsedSource as Partial<DesktopSFTPBatchOperationError>);
    }
}

export class DesktopSFTPChmodInput {
    "serverId": string;
    "path": string;
    "mode": string;

    /** Creates a new DesktopSFTPChmodInput instance. */
    constructor($$source: Partial<DesktopSFTPChmodInput> = {}) {
        if (!("serverId" in $$source)) {
            this["serverId"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("mode" in $$source)) {
            this["mode"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DesktopSFTPChmodInput instance from a string or object.
     */
    static createFrom($$source: any = {}): DesktopSFTPChmodInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DesktopSFTPChmodInput($$parsedSource as Partial<DesktopSFTPChmodInput>);
    }
}

export class DesktopSFTPDirectTransferInput {
    "sourceServerId": string;
    "sourcePath": string;
    "targetServerId": string;
    "targetPath": string;

    /** Creates a new DesktopSFTPDirectTransferInput instance. */
    constructor($$source: Partial<DesktopSFTPDirectTransferInput> = {}) {
        if (!("sourceServerId" in $$source)) {
            this["sourceServerId"] = "";
        }
        if (!("sourcePath" in $$source)) {
            this["sourcePath"] = "";
        }
        if (!("targetServerId" in $$source)) {
            this["targetServerId"] = "";
        }
        if (!("targetPath" in $$source)) {
            this["targetPath"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DesktopSFTPDirectTransferInput instance from a string or object.
     */
    static createFrom($$source: any = {}): DesktopSFTPDirectTransferInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DesktopSFTPDirectTransferInput($$parsedSource as Partial<DesktopSFTPDirectTransferInput>);
    }
}

export class DesktopSFTPDirectTransferResult {
    "success": boolean;
    "task_id": string;
    "message": string;

    /** Creates a new DesktopSFTPDirectTransferResult instance. */
    constructor($$source: Partial<DesktopSFTPDirectTransferResult> = {}) {
        if (!("success" in $$source)) {
            this["success"] = false;
        }
        if (!("task_id" in $$source)) {
            this["task_id"] = "";
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DesktopSFTPDirectTransferResult instance from a string or object.
     */
    static createFrom($$source: any = {}): DesktopSFTPDirectTransferResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DesktopSFTPDirectTransferResult($$parsedSource as Partial<DesktopSFTPDirectTransferResult>);
    }
}

export class DesktopSFTPDirectoryListResult {
    "path": string;
    "files": DesktopSFTPFileInfo[];
    "parent"?: string;

    /** Creates a new DesktopSFTPDirectoryListResult instance. */
    constructor($$source: Partial<DesktopSFTPDirectoryListResult> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("files" in $$source)) {
            this["files"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DesktopSFTPDirectoryListResult instance from a string or object.
     */
    static createFrom($$source: any = {}): DesktopSFTPDirectoryListResult {
        const $$createField1_0 = $$createType41;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("files" in $$parsedSource) {
            $$parsedSource["files"] = $$createField1_0($$parsedSource["files"]);
        }
        return new DesktopSFTPDirectoryListResult($$parsedSource as Partial<DesktopSFTPDirectoryListResult>);
    }
}

export class DesktopSFTPDownloadFileInput {
    "serverId": string;
    "path": string;
    "localPath": string;

    /** Creates a new DesktopSFTPDownloadFileInput instance. */
    constructor($$source: Partial<DesktopSFTPDownloadFileInput> = {}) {
        if (!("serverId" in $$source)) {
            this["serverId"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("localPath" in $$source)) {
            this["localPath"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DesktopSFTPDownloadFileInput instance from a string or object.
     */
    static createFrom($$source: any = {}): DesktopSFTPDownloadFileInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DesktopSFTPDownloadFileInput($$parsedSource as Partial<DesktopSFTPDownloadFileInput>);
    }
}

export class DesktopSFTPFileInfo {
    "name": string;
    "path": string;
    "size": number;
    "mode": number;
    "mod_time": string;
    "is_dir": boolean;
    "is_link": boolean;
    "link_target"?: string;
    "permission"?: string;

    /** Creates a new DesktopSFTPFileInfo instance. */
    constructor($$source: Partial<DesktopSFTPFileInfo> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("size" in $$source)) {
            this["size"] = 0;
        }
        if (!("mode" in $$source)) {
            this["mode"] = 0;
        }
        if (!("mod_time" in $$source)) {
            this["mod_time"] = "";
        }
        if (!("is_dir" in $$source)) {
            this["is_dir"] = false;
        }
        if (!("is_link" in $$source)) {
            this["is_link"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DesktopSFTPFileInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): DesktopSFTPFileInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DesktopSFTPFileInfo($$parsedSource as Partial<DesktopSFTPFileInfo>);
    }
}

export class DesktopSFTPPathInput {
    "serverId": string;
    "path": string;

    /** Creates a new DesktopSFTPPathInput instance. */
    constructor($$source: Partial<DesktopSFTPPathInput> = {}) {
        if (!("serverId" in $$source)) {
            this["serverId"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DesktopSFTPPathInput instance from a string or object.
     */
    static createFrom($$source: any = {}): DesktopSFTPPathInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DesktopSFTPPathInput($$parsedSource as Partial<DesktopSFTPPathInput>);
    }
}

export class DesktopSFTPRenameInput {
    "serverId": string;
    "oldPath": string;
    "newPath": string;

    /** Creates a new DesktopSFTPRenameInput instance. */
    constructor($$source: Partial<DesktopSFTPRenameInput> = {}) {
        if (!("serverId" in $$source)) {
            this["serverId"] = "";
        }
        if (!("oldPath" in $$source)) {
            this["oldPath"] = "";
        }
        if (!("newPath" in $$source)) {
            this["newPath"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DesktopSFTPRenameInput instance from a string or object.
     */
    static createFrom($$source: any = {}): DesktopSFTPRenameInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DesktopSFTPRenameInput($$parsedSource as Partial<DesktopSFTPRenameInput>);
    }
}

export class DesktopSFTPUploadFileInput {
    "serverId": string;
    "path": string;
    "fileName": string;
    "data": string;

    /** Creates a new DesktopSFTPUploadFileInput instance. */
    constructor($$source: Partial<DesktopSFTPUploadFileInput> = {}) {
        if (!("serverId" in $$source)) {
            this["serverId"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("fileName" in $$source)) {
            this["fileName"] = "";
        }
        if (!("data" in $$source)) {
            this["data"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DesktopSFTPUploadFileInput instance from a string or object.
     */
    static createFrom($$source: any = {}): DesktopSFTPUploadFileInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DesktopSFTPUploadFileInput($$parsedSource as Partial<DesktopSFTPUploadFileInput>);
    }
}

export class DesktopSFTPUploadTaskListResult {
    "tasks": DesktopSFTPUploadTaskStatus[];

    /** Creates a new DesktopSFTPUploadTaskListResult instance. */
    constructor($$source: Partial<DesktopSFTPUploadTaskListResult> = {}) {
        if (!("tasks" in $$source)) {
            this["tasks"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DesktopSFTPUploadTaskListResult instance from a string or object.
     */
    static createFrom($$source: any = {}): DesktopSFTPUploadTaskListResult {
        const $$createField0_0 = $$createType43;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tasks" in $$parsedSource) {
            $$parsedSource["tasks"] = $$createField0_0($$parsedSource["tasks"]);
        }
        return new DesktopSFTPUploadTaskListResult($$parsedSource as Partial<DesktopSFTPUploadTaskListResult>);
    }
}

export class DesktopSFTPUploadTaskStatus {
    "id": string;
    "file_name": string;
    "file_size": number;
    "status": string;
    "progress": number;
    "loaded": number;
    "total": number;
    "speed_bps": number;
    "created_at": string;
    "updated_at": string;

    /** Creates a new DesktopSFTPUploadTaskStatus instance. */
    constructor($$source: Partial<DesktopSFTPUploadTaskStatus> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("file_name" in $$source)) {
            this["file_name"] = "";
        }
        if (!("file_size" in $$source)) {
            this["file_size"] = 0;
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("progress" in $$source)) {
            this["progress"] = 0;
        }
        if (!("loaded" in $$source)) {
            this["loaded"] = 0;
        }
        if (!("total" in $$source)) {
            this["total"] = 0;
        }
        if (!("speed_bps" in $$source)) {
            this["speed_bps"] = 0;
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = "";
        }
        if (!("updated_at" in $$source)) {
            this["updated_at"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DesktopSFTPUploadTaskStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): DesktopSFTPUploadTaskStatus {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DesktopSFTPUploadTaskStatus($$parsedSource as Partial<DesktopSFTPUploadTaskStatus>);
    }
}

export class DesktopSFTPWriteFileInput {
    "serverId": string;
    "path": string;
    "content": string;

    /** Creates a new DesktopSFTPWriteFileInput instance. */
    constructor($$source: Partial<DesktopSFTPWriteFileInput> = {}) {
        if (!("serverId" in $$source)) {
            this["serverId"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("content" in $$source)) {
            this["content"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DesktopSFTPWriteFileInput instance from a string or object.
     */
    static createFrom($$source: any = {}): DesktopSFTPWriteFileInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DesktopSFTPWriteFileInput($$parsedSource as Partial<DesktopSFTPWriteFileInput>);
    }
}

export class DesktopSaveUserAIConfigRequest {
    "use_system_config": boolean;
    "custom_enabled": boolean;
    "custom_provider": string;
    "custom_api_key": string;
    "custom_endpoint": string;
    "custom_models": string;

    /** Creates a new DesktopSaveUserAIConfigRequest instance. */
    constructor($$source: Partial<DesktopSaveUserAIConfigRequest> = {}) {
        if (!("use_system_config" in $$source)) {
            this["use_system_config"] = false;
        }
        if (!("custom_enabled" in $$source)) {
            this["custom_enabled"] = false;
        }
        if (!("custom_provider" in $$source)) {
            this["custom_provider"] = "";
        }
        if (!("custom_api_key" in $$source)) {
            this["custom_api_key"] = "";
        }
        if (!("custom_endpoint" in $$source)) {
            this["custom_endpoint"] = "";
        }
        if (!("custom_models" in $$source)) {
            this["custom_models"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DesktopSaveUserAIConfigRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): DesktopSaveUserAIConfigRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DesktopSaveUserAIConfigRequest($$parsedSource as Partial<DesktopSaveUserAIConfigRequest>);
    }
}

export class DesktopServer {
    "id": string;
    "user_id": string;
    "name"?: string;
    "host": string;
    "port": number;
    "username": string;
    "auth_method": DesktopServerAuthMethod;
    "password"?: string;
    "private_key"?: string;
    "group"?: string;
    "tags"?: string[];
    "status": DesktopServerStatus;
    "last_connected"?: string;
    "description"?: string;
    "created_at": string;
    "updated_at": string;

    /** Creates a new DesktopServer instance. */
    constructor($$source: Partial<DesktopServer> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("user_id" in $$source)) {
            this["user_id"] = "";
        }
        if (!("host" in $$source)) {
            this["host"] = "";
        }
        if (!("port" in $$source)) {
            this["port"] = 0;
        }
        if (!("username" in $$source)) {
            this["username"] = "";
        }
        if (!("auth_method" in $$source)) {
            this["auth_method"] = DesktopServerAuthMethod.$zero;
        }
        if (!("status" in $$source)) {
            this["status"] = DesktopServerStatus.$zero;
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = "";
        }
        if (!("updated_at" in $$source)) {
            this["updated_at"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DesktopServer instance from a string or object.
     */
    static createFrom($$source: any = {}): DesktopServer {
        const $$createField10_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField10_0($$parsedSource["tags"]);
        }
        return new DesktopServer($$parsedSource as Partial<DesktopServer>);
    }
}

export enum DesktopServerAuthMethod {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    DesktopServerAuthPassword = "password",
    DesktopServerAuthKey = "key",
};

export class DesktopServerCommandInput {
    "serverId": string;
    "command": string;
    "timeoutMs"?: number;

    /** Creates a new DesktopServerCommandInput instance. */
    constructor($$source: Partial<DesktopServerCommandInput> = {}) {
        if (!("serverId" in $$source)) {
            this["serverId"] = "";
        }
        if (!("command" in $$source)) {
            this["command"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DesktopServerCommandInput instance from a string or object.
     */
    static createFrom($$source: any = {}): DesktopServerCommandInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DesktopServerCommandInput($$parsedSource as Partial<DesktopServerCommandInput>);
    }
}

export class DesktopServerCommandResult {
    "serverId": string;
    "command": string;
    "output": string;
    "exitCode": number;
    "durationMs": number;
    "startedAt": string;
    "completedAt": string;

    /** Creates a new DesktopServerCommandResult instance. */
    constructor($$source: Partial<DesktopServerCommandResult> = {}) {
        if (!("serverId" in $$source)) {
            this["serverId"] = "";
        }
        if (!("command" in $$source)) {
            this["command"] = "";
        }
        if (!("output" in $$source)) {
            this["output"] = "";
        }
        if (!("exitCode" in $$source)) {
            this["exitCode"] = 0;
        }
        if (!("durationMs" in $$source)) {
            this["durationMs"] = 0;
        }
        if (!("startedAt" in $$source)) {
            this["startedAt"] = "";
        }
        if (!("completedAt" in $$source)) {
            this["completedAt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DesktopServerCommandResult instance from a string or object.
     */
    static createFrom($$source: any = {}): DesktopServerCommandResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DesktopServerCommandResult($$parsedSource as Partial<DesktopServerCommandResult>);
    }
}

export class DesktopServerInput {
    "name"?: string;
    "host": string;
    "port": number;
    "username": string;
    "auth_method": DesktopServerAuthMethod;
    "password"?: string;
    "private_key"?: string;
    "group"?: string;
    "tags"?: string[];
    "description"?: string;

    /** Creates a new DesktopServerInput instance. */
    constructor($$source: Partial<DesktopServerInput> = {}) {
        if (!("host" in $$source)) {
            this["host"] = "";
        }
        if (!("port" in $$source)) {
            this["port"] = 0;
        }
        if (!("username" in $$source)) {
            this["username"] = "";
        }
        if (!("auth_method" in $$source)) {
            this["auth_method"] = DesktopServerAuthMethod.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DesktopServerInput instance from a string or object.
     */
    static createFrom($$source: any = {}): DesktopServerInput {
        const $$createField8_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField8_0($$parsedSource["tags"]);
        }
        return new DesktopServerInput($$parsedSource as Partial<DesktopServerInput>);
    }
}

export class DesktopServerListParams {
    "page"?: number;
    "limit"?: number;
    "search"?: string;
    "group"?: string;

    /** Creates a new DesktopServerListParams instance. */
    constructor($$source: Partial<DesktopServerListParams> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DesktopServerListParams instance from a string or object.
     */
    static createFrom($$source: any = {}): DesktopServerListParams {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DesktopServerListParams($$parsedSource as Partial<DesktopServerListParams>);
    }
}

export class DesktopServerListResult {
    "data": DesktopServer[];
    "total": number;
    "page": number;
    "limit": number;

    /** Creates a new DesktopServerListResult instance. */
    constructor($$source: Partial<DesktopServerListResult> = {}) {
        if (!("data" in $$source)) {
            this["data"] = [];
        }
        if (!("total" in $$source)) {
            this["total"] = 0;
        }
        if (!("page" in $$source)) {
            this["page"] = 0;
        }
        if (!("limit" in $$source)) {
            this["limit"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DesktopServerListResult instance from a string or object.
     */
    static createFrom($$source: any = {}): DesktopServerListResult {
        const $$createField0_0 = $$createType45;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("data" in $$parsedSource) {
            $$parsedSource["data"] = $$createField0_0($$parsedSource["data"]);
        }
        return new DesktopServerListResult($$parsedSource as Partial<DesktopServerListResult>);
    }
}

export enum DesktopServerStatus {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    DesktopServerOnline = "online",
    DesktopServerOffline = "offline",
};

export class DesktopTerminalCloseInput {
    "clientId": string;

    /** Creates a new DesktopTerminalCloseInput instance. */
    constructor($$source: Partial<DesktopTerminalCloseInput> = {}) {
        if (!("clientId" in $$source)) {
            this["clientId"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DesktopTerminalCloseInput instance from a string or object.
     */
    static createFrom($$source: any = {}): DesktopTerminalCloseInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DesktopTerminalCloseInput($$parsedSource as Partial<DesktopTerminalCloseInput>);
    }
}

export class DesktopTerminalPingInput {
    "clientId": string;

    /** Creates a new DesktopTerminalPingInput instance. */
    constructor($$source: Partial<DesktopTerminalPingInput> = {}) {
        if (!("clientId" in $$source)) {
            this["clientId"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DesktopTerminalPingInput instance from a string or object.
     */
    static createFrom($$source: any = {}): DesktopTerminalPingInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DesktopTerminalPingInput($$parsedSource as Partial<DesktopTerminalPingInput>);
    }
}

export class DesktopTerminalPingResult {
    "latencyMs": number;
    "measuredAt": number;

    /** Creates a new DesktopTerminalPingResult instance. */
    constructor($$source: Partial<DesktopTerminalPingResult> = {}) {
        if (!("latencyMs" in $$source)) {
            this["latencyMs"] = 0;
        }
        if (!("measuredAt" in $$source)) {
            this["measuredAt"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DesktopTerminalPingResult instance from a string or object.
     */
    static createFrom($$source: any = {}): DesktopTerminalPingResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DesktopTerminalPingResult($$parsedSource as Partial<DesktopTerminalPingResult>);
    }
}

export class DesktopTerminalResizeInput {
    "clientId": string;
    "cols": number;
    "rows": number;

    /** Creates a new DesktopTerminalResizeInput instance. */
    constructor($$source: Partial<DesktopTerminalResizeInput> = {}) {
        if (!("clientId" in $$source)) {
            this["clientId"] = "";
        }
        if (!("cols" in $$source)) {
            this["cols"] = 0;
        }
        if (!("rows" in $$source)) {
            this["rows"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DesktopTerminalResizeInput instance from a string or object.
     */
    static createFrom($$source: any = {}): DesktopTerminalResizeInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DesktopTerminalResizeInput($$parsedSource as Partial<DesktopTerminalResizeInput>);
    }
}

export class DesktopTerminalStartInput {
    "clientId": string;
    "serverId": string;
    "cols": number;
    "rows": number;

    /** Creates a new DesktopTerminalStartInput instance. */
    constructor($$source: Partial<DesktopTerminalStartInput> = {}) {
        if (!("clientId" in $$source)) {
            this["clientId"] = "";
        }
        if (!("serverId" in $$source)) {
            this["serverId"] = "";
        }
        if (!("cols" in $$source)) {
            this["cols"] = 0;
        }
        if (!("rows" in $$source)) {
            this["rows"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DesktopTerminalStartInput instance from a string or object.
     */
    static createFrom($$source: any = {}): DesktopTerminalStartInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DesktopTerminalStartInput($$parsedSource as Partial<DesktopTerminalStartInput>);
    }
}

export class DesktopTerminalWriteInput {
    "clientId": string;
    "data": string;

    /** Creates a new DesktopTerminalWriteInput instance. */
    constructor($$source: Partial<DesktopTerminalWriteInput> = {}) {
        if (!("clientId" in $$source)) {
            this["clientId"] = "";
        }
        if (!("data" in $$source)) {
            this["data"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DesktopTerminalWriteInput instance from a string or object.
     */
    static createFrom($$source: any = {}): DesktopTerminalWriteInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DesktopTerminalWriteInput($$parsedSource as Partial<DesktopTerminalWriteInput>);
    }
}

export class DesktopUserAIConfig {
    "use_system_config": boolean;
    "custom_enabled": boolean;
    "custom_provider": string;
    "custom_endpoint": string;
    "custom_models": string;
    "has_api_key": boolean;

    /** Creates a new DesktopUserAIConfig instance. */
    constructor($$source: Partial<DesktopUserAIConfig> = {}) {
        if (!("use_system_config" in $$source)) {
            this["use_system_config"] = false;
        }
        if (!("custom_enabled" in $$source)) {
            this["custom_enabled"] = false;
        }
        if (!("custom_provider" in $$source)) {
            this["custom_provider"] = "";
        }
        if (!("custom_endpoint" in $$source)) {
            this["custom_endpoint"] = "";
        }
        if (!("custom_models" in $$source)) {
            this["custom_models"] = "";
        }
        if (!("has_api_key" in $$source)) {
            this["has_api_key"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DesktopUserAIConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): DesktopUserAIConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DesktopUserAIConfig($$parsedSource as Partial<DesktopUserAIConfig>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = DesktopAISessionScope.createFrom;
const $$createType2 = $Create.Nullable($$createType1);
const $$createType3 = DesktopAISessionView.createFrom;
const $$createType4 = DesktopAISessionListItem.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = DesktopAIMessageView.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = DesktopAITaskView.createFrom;
const $$createType9 = $Create.Array($$createType8);
const $$createType10 = $Create.Map($Create.Any, $Create.Any);
const $$createType11 = $Create.Array($$createType10);
const $$createType12 = DesktopAIToolView.createFrom;
const $$createType13 = $Create.Array($$createType12);
const $$createType14 = DesktopActivityLogItem.createFrom;
const $$createType15 = $Create.Array($$createType14);
const $$createType16 = $Create.Map($Create.Any, $Create.Any);
const $$createType17 = DesktopDockerPort.createFrom;
const $$createType18 = $Create.Array($$createType17);
const $$createType19 = $Create.Map($Create.Any, $Create.Any);
const $$createType20 = DesktopDockerMount.createFrom;
const $$createType21 = $Create.Array($$createType20);
const $$createType22 = DesktopDockerContainer.createFrom;
const $$createType23 = $Create.Array($$createType22);
const $$createType24 = DesktopDockerImage.createFrom;
const $$createType25 = $Create.Array($$createType24);
const $$createType26 = DesktopDockerContainerStats.createFrom;
const $$createType27 = $Create.Array($$createType26);
const $$createType28 = DesktopDockerSystemInfo.createFrom;
const $$createType29 = $Create.Nullable($$createType28);
const $$createType30 = DesktopMonitorSystemInfo.createFrom;
const $$createType31 = DesktopMonitorCPUInfo.createFrom;
const $$createType32 = DesktopMonitorMemoryInfo.createFrom;
const $$createType33 = DesktopMonitorNetworkInfo.createFrom;
const $$createType34 = DesktopMonitorDiskInfo.createFrom;
const $$createType35 = $Create.Array($$createType34);
const $$createType36 = DesktopMonitorDockerInfo.createFrom;
const $$createType37 = $Create.Map($Create.Any, $Create.Any);
const $$createType38 = DesktopSFTPBatchOperationError.createFrom;
const $$createType39 = $Create.Array($$createType38);
const $$createType40 = DesktopSFTPFileInfo.createFrom;
const $$createType41 = $Create.Array($$createType40);
const $$createType42 = DesktopSFTPUploadTaskStatus.createFrom;
const $$createType43 = $Create.Array($$createType42);
const $$createType44 = DesktopServer.createFrom;
const $$createType45 = $Create.Array($$createType44);
