allowBuilds:
  '@parcel/watcher': true
  '@swc/core': true
  '@tailwindcss/oxide': true
  '@tsparticles/engine': true
  '@vercel/speed-insights': true
  esbuild: true
  msw: true
  protobufjs: true
  sharp: true
  unrs-resolver: true
packages:
  - packages/*
overrides:
  '@assistant-ui/core': 0.3.17
  '@assistant-ui/store': 0.3.14
  '@assistant-ui/tap': 0.9.18
